### ISSUE TITLE
Make recent chat messages visible to people who have just logged on

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#1003]
This would be a measure for now, so that when I am in the game, I can see if there has been recent activity, and leave a greeting so if other people log on, they see I might be around.

I'm not sure how long messages should persist. Maybe around 2 hours, as I often leave the game open while I do other work.

**Comment by Zach777** [comment]
Should we require people to set a name before starting the game? You would probably just get an occasional No Name Set asking if anyone is online.
