### ISSUE TITLE
Set up astronaut

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#1005]
Create a version of players with a spacesuit on. 

For now the spacesuit version will simply appear when players are in the airlock. A tooltip will advise that going through an airlock is actually a long process and difficult technical hurdles need to be overcome to bring that down, and anyways it would usually be better to work by remote operation.

**Comment by Zach777** [comment]
@Moonwards 
Do we still want to make it just appear on players when opening an airlock? Tbh I was going to make people have to get into a suit before opening an airlock.
 Either way is about the same amount of work.

**Comment by Moonwards** [comment]
@Zach777 
So it would appear on them when they click on something near an airlock? Yes, that is more accurate and natural. 

So that means setting up some little sign or something near each airlock, right?

**Comment by Zach777** [comment]
Well either way, the Airlock has to know if it is safe to open the door. That means I have to check for unsuited players before opening the outdoor airlock.
 So any solution takes the same amount of work.

**Comment by Moonwards** [comment]
The spacesuit still needs a jump animation and a flail animation to be adapted. Those should be quick. 

I take it it should be possible to drop that in as it should be identical in structure to the existing player animations, so the animation tree already has that.

**Comment by Moonwards** [comment]
@Zach777 The jump and flail animations are in place, and I did that without removing unused animations because when I did that the animation tree broke.

**Comment by Zach777** [comment]
Resolved by PR #1022
