### ISSUE TITLE
Set up 'remote operation' of androids through kiosks

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#1007]
Once a player has activated remote control through a kiosk, their POV must jump to an android. In the first iteration, they will always switch to the same new place somewhere outside - near the main factories where in the story androids would most often be needed. Later they should be able to select from androids in a variety of locations.

**Comment by Zach777** [comment]
@Moonwards For now I will make it where there is one kiosk for each Android. It will make it easier to return Androids to the correct location.
 Should Androids be able to run faster than humans?

**Comment by Moonwards** [comment]
@Zach777 
The androids aren't rigged, it continues to be a problem. I was going to make a kiosk model for the next release, and plan to have the rigging done for that too. If we want to do it for this release, it could be up to several days for me to figure out the rigging, while there are a lot of other kinds of work for me to do. I would rather leave it for the next release so I can put in some solid time on preparing upcoming marketing and networking. 

The kiosks can go anywhere, this is part of the design question. Considering androids would often be used for work reasons, it would be easiest if kiosks were where people work so co-workers can see the info coming in and talk it over real time, and it's handy to go back and forth between android control and other work. We haven't modelled any labs or workshops yet, so I was going to put the first few in the neighborhood and scattered around a bit. 

Yes, both androids and spacesuits can run faster than humans. The spacesuit has a powered exoskeleton. I have to go out now, but we can talk about it later in the day today.

**Comment by Moonwards** [comment]
The androids are now rigged and have all the walking animations done. 

The jump and flail animations can also be done, but it would be good to see first how the animation tree needs adapting for the android, because the armature is not the same. I've structured the animations as the same length as the existing player animations. So perhaps it can simply be copied. I've never worked with animation players so will need guidance on this. I'll be looking at a tutorial on them in the morning.
