### ISSUE TITLE
Android spawning

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#1026]
There are a series of android depots at various points outdoors, and one in Long Dome as it is an exceptionally large hab. 

First Factory
Long Dome
Main Factory
Outside 2nd Gallery
STEMP Facilities
Spaceport

6 locations of depots.  The remaining slots could be for androids located inside habs.

**Comment by Moonwards** [comment]
@Zach777 If we use the remaining slots for androids inside the habs, then can we make it like the way they work for the depots - that it doesn't connect to a specific android, but just spawns a new one for everyone who wants one, all of them starting in the same spot?

I do think it will be desirable in the future for androids to be persistent, but later on.

**Comment by Zach777** [comment]
@briligg We can have it either spawn an Android or just have an Android staying in that location permanently.
 I suggest spawning and despawning the Androids for now.

**Comment by Moonwards** [comment]
I was thinking of having the androids spawn where they are placed already, so that they overlap when someone spawns there. At least it indicates that they are from the android equipment stationed there.
