### ISSUE TITLE
Errors in gamestate.gd

### ISSUE THREAD

**Issue by SiudaPL** [moonwards1/Moonwards-Virtual-Moon#103]
While hosting a custom game there are some errors regarding functions in gamestate.gd.

I recommend browsing the errors and fix them for better game integrity.

Switch back issue to me.

**Comment by SiudaPL** [comment]
Fixed:
- log_all_signals_print_x type casting errors -> it's best not to specify argument type here and function will handle anything in correct manner.
- Error calling method from signal 'log_gamestate' -> previous signal name is 'gslog', so now it should be 'gamestate_log'. Sometimes signal is referenced as 'log_gamestate' so it's causing confusion. All calls unified to `gamestate_log`.

In Pull Request: #106

**Comment by Gyrth** [comment]
![image](https://user-images.githubusercontent.com/14081613/68551673-95a72080-040f-11ea-850c-6ac6c02644c3.png)
A lot of the errors that are thrown in gamestate.as are because of the Viewport textures. I think this can be ignored, but I hope this error is fixed in 3.2.

**Comment by TheDuriel** [comment]
that particular error can be solved with some knob tweaking of the viewport texture resource, or by creating it at runtime. ill take a look at it.

**Comment by yaelatletl** [comment]
I haven't got any crashes, perhaps we should make a small online test to check if anything happens?

**Comment by Gyrth** [comment]
@TheDuriel the nice thing about creating a ViewportTexture in the editor is that you can see the result immediately. So if you could make it work with just some settings tweak then that would be great.

**Comment by TheDuriel** [comment]
Viewport textures need the "make_local" setting set, or they will produce an endless stream of errors. We can still keep the texture assigned in the editor, for previewing. But reassign it an runtime during _ready to avoid errors.

**Comment by yaelatletl** [comment]
Spotted this guy as client

ERROR: _process_get_node: Failed to get cached path from RPC: world/players/1
   At: core/io/multiplayer_api.cpp:266
ERROR: Invalid packet received. Requested node was not found.
   At: core/io/multiplayer_api.cpp:194
ERROR: Node not found: world/players/1

**Comment by yaelatletl** [comment]
This was solved with #168 and #151
