### ISSUE TITLE
New game server

### ISSUE THREAD

**Issue by SiudaPL** [moonwards1/Moonwards-Virtual-Moon#111]
Setting up a new game server on Google Cloud.
3 servers as follows: 

- 1st for storage, like game builds (execs) and for the launcher and its files;
- 2nd wit stable server build, the one that we would only fix critical issues, no new features;
- 3rd with current / development server build, the most fresh stuff we have (probably will mirror master in git).

**Comment by Gyrth** [comment]
Please send me the SSH details so I can setup the Launcher requirements.

**Comment by TheDuriel** [comment]
They both still deal with saving and loading screen sizes and modes.

Overall the files are quite a mess. autoload-options seems to try to be responsible for saving and loading options in general. However settings.gd does the same.

We should probably make a single persistence singleton, using config file, which can deal with user settings. And then make the UI a controller for it. (MVC model)

**Comment by SiudaPL** [comment]
**TODO**
Add server builds and headless Godot versions to `gitignore`

**Comment by SiudaPL** [comment]
**TODO** with Git ignores
in PR: #131

**Comment by SiudaPL** [comment]
Git ignores skipped.
New Pull Request in PR #132 with export directories
