### ISSUE TITLE
Implement New Logger

### ISSUE THREAD

**Issue by TheDuriel** [moonwards1/Moonwards-Virtual-Moon#113]
As discussed in #107

**Comment by Gyrth** [comment]
`if LOG_LEVEL >= level:`

Why did you add this if statement? Won't this always be true if you set LOG_LEVEL to the highest possible enum value?

**Comment by Gyrth** [comment]
Would there also be a need to have a Log viewer in-game? For example pressing F2 will popup a Log window where you can scroll through the Log and show/hide Log types. 

And second, when the game crashes, would it be possible to output the Log to a file before it actually closes?

**Comment by Gyrth** [comment]
![image](https://user-images.githubusercontent.com/14081613/68675484-40c2f180-0558-11ea-975b-0742b8a44ed3.png)
I've been working on the Logger and it's UI. I had some difficulties with it using static functions but it seems to work now. You can show/hide specific Log types. And you can toggle it with F3.

**Comment by TheDuriel** [comment]
Nice.

We can write the log to disk continuously, using store_line() calls each time a message is emitted. the worst thing that can result from this is the game crashing while the file is being written to. which _could_ corrupt it. (But it really should not.)

We can also listen to the exit notification emitted by the OS, to make sure we close the file stream when the application closes.

I'll pull your branch later and see how to go about making those changes. The coupling between UI and log seems a bit odd as well.

**Comment by Gyrth** [comment]
I think writing when the game crashes/closes wouldn't always work. It's probably saver to keep a log file open and add to it every time a log message is send. The downside of that would be a log being written every time the user opens Moonwards. What do you think is the best approach?

**Comment by TheDuriel** [comment]
implemented by #117
