### ISSUE TITLE
Logger I/O Error

### ISSUE THREAD

**Issue by SiudaPL** [moonwards1/Moonwards-Virtual-Moon#129]
On Linux (both `localhost` and `cloud instance`) the logger can't access the logging file:

`_ERROR: Logger: _open_log_file, cant open user://logs/2019-11-26-11-4-38.txt. File logging suspended.`

For the `local` build, when you select hosting the game in UI - the game works (even with the error). For the `headless server` build the game server won't start. Launching the `headless server` even cleans info about the Godot projects on my PC.

The `headless server` console don't print a hint:
`options.gd  :: load options and settings`
which my be the cause why server doesn't start.

**Comment by TheDuriel** [comment]
the open() call returns a status code constant. check what it is here http://docs.godotengine.org/en/latest/classes/class_@globalscope.html. it is possible that you have no write permissions in the user:// directory.

**Comment by SiudaPL** [comment]
There was a manual directory creation that was different then previously declared constant LOG_DIR. This situation created two separate directories: `logs` and `Logs`.

Fix in PR: #130
