### ISSUE TITLE
stuck on Rocket display

### ISSUE THREAD

**Issue by yaelatletl** [moonwards1/Moonwards-Virtual-Moon#149]
Can't use the UI, and can't leave either. So once you start the showcase you can no longer get out of it.

**Comment by TheDuriel** [comment]
Expected. Caused by https://github.com/moonwards1/Moonwards-Virtual-Moon/commit/119577afc9fc8df4e66b7533a259fead171313a2

an overhaul of how to handle the mouse state is required. for now the commented out code can be replaced with setting the correct mouse state.
