### ISSUE TITLE
When resizing window the window when the game is paused and the Options tab is set to Player, game environment becomes darker

### ISSUE THREAD

**Issue by Zach777** [moonwards1/Moonwards-Virtual-Moon#163]
Start game via local host, then pause the game and go to Options.
 Switch tab to Player and resize the window. Notice that the entire game environment becomes darker. This bug persists even after you exit the pause menu.
 To fix the bug in game, switch the Options tab to Settings and resize the window. Alternatively, change the game resolution via the resolution switch in the Settings tab.

**Comment by TheDuriel** [comment]
Can't reproduce this on #d4e5d473ebe7c1b042f7c22f06b56904b51dbaf3

**Comment by Zach777** [comment]
Just checked on the master branch and it is still there. Are you sure you were resizing the window itself instead of using the built in resolution switcher?
 It only occurs if you resize the window (by dragging the window at the edges of the screen) while the Player tab is active in the pause menu for me.

**Comment by TheDuriel** [comment]
Yes. I hosted a local game and resized the window with every options tab open.

**Comment by Moonwards** [comment]
I can't reproduce it either. I thought it might be a Linux thing, but my system is Ubuntu and also doesn't display this behaviour.

**Comment by Zach777** [comment]
I am using integrated graphics so that might have something to do with it. 
  Just to verify,  you paused the game, clicked on Options, clicked on "Player" tab, then resized the window via dragging the corner of the screen?
 If that did not cause the bug, then it is a hardware related issue with the game/engine.

**Comment by Moonwards** [comment]
Yes, I paused, clicked options, and tried dragging the corners of the window while each of the tabs was open, and never saw a darkening. I also tried moving around in the game to see if lighting conditions were a factor. I haven't seen anything.
