### ISSUE TITLE
Separate MenuSignals from HudSignals

### ISSUE THREAD

**Issue by Reousa** [moonwards1/Moonwards-Virtual-Moon#260]
Add a new "HudSignals" signals manager, to give some contrast between HUD specific signals & general menu signals.

Tool tips should be in the HUD category.

**Comment by Zach777** [comment]
Would Pause be considered Hud or Menu?

**Comment by Reousa** [comment]
if you're referring to the `PauseMenu` then that's a menu, so it belongs in menus :P.

Generally speaking, HUD is this that appear on the screen that the player interact with, that are not menus. Things like stat bars, informational messages, chat, etc.

This is to categorize things that change game state (such as logging out, or switching graphics options etc) from things the player would use to _play_ the game.
