### ISSUE TITLE
Add menu events for network based interactions

### ISSUE THREAD

**Issue by Reousa** [moonwards1/Moonwards-Virtual-Moon#263]
Add menu events for things like `Join server` or `Host local` etc.
Network events will remain parameterless for now.

**Comment by Zach777** [comment]
What all signals are needed?
How should I setup the signals?

**Comment by Reousa** [comment]
Hold on this for now, we'll get back to it once we have events the menus can emit & subscribe to.

**Comment by Reousa** [comment]
Added in a different manner - closing.
