### ISSUE TITLE
Make Main Menu follow the GDD's structure.

### ISSUE THREAD

**Issue by Zach777** [moonwards1/Moonwards-Virtual-Moon#268]
Have the main menu reflect this concept art: https://cdn.discordapp.com/attachments/506624914694864898/701135087454126080/unknown.png

Except make the buttons and panels darker to fit with the aesthetic. Possibly make the buttons and panels reflect their design in their current state with how they have near black and opaque backs.

Initial reference from GDD: https://github.com/moonwards1/Moonwards-Virtual-Moon/wiki/Player-Experience
- [x] Example task
- [x] Example task 2

**Comment by Reousa** [comment]
Can we update progress on this issue? @Zach777 @Moonwards

**Comment by Zach777** [comment]
Pretty certain this issue is completed. The main menu now looks like what is recommended in the gdd.

**Comment by Moonwards** [comment]
@Zach777  @Reousa I regarded the menu as temporary as most of the planned contents don't exist.  But why does it label things the way it does instead of following the list i put in the GDD? And why not put in all the buttons and just grey out the things that don't exist yet - after all, the main point of this is to shop it around, i want future plans to be evident.

**Comment by Zach777** [comment]
I will make greyed out buttons after I get nametags done. The menu was temporary, I was just going to add a new issue for when we improve it.

**Comment by Reousa** [comment]
We'll use the same issue card, break down the tasks further in this card instead of a new one.

Since we're recreating it, please follow the new standard. Clean naming, good comments & structure will be required post demo-rewrite.

**Comment by Reousa** [comment]
Update on this? @Zach777 @Moonwards

**Comment by Zach777** [comment]
Should I make the buttons greyed out? Right now we cannot add much to the menus since the rest of the features have not been completed.

**Comment by Moonwards** [comment]
Yes, @Zach777 IMO better to have them there and greyed out - so anyone who tries it right now gets a sense of where it will go in the future.
