### ISSUE TITLE
Develop NPCs

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#269]
A variety of NPCs are meant to be added over time, some of them quite complex. This is an area where a highly adaptable framework is important. The aim is to create a system that allows contribution of modified NPCs by advanced users down the road.

Initially the goal is simply to have a few NPCs just walking around, either in set loops or with path-finding behaviors. They should exist in First Gallery, the RecHab, Center Atrium, First Atrium, Rim Arcade, Teacup Crater, and the Spaceport. As objects and animations are added, they will need to be updated with increasingly complex behavior. 

Character models need to be made for them, at first they can be simple player models with different colors.

Attaching audio clips to the NPCs would be the next step. Some intro clip should play when a player is within a certain distance, and then further clips will play if the player follows the NPC, or interacts with a relevant object, or in some cases just remains near enough.

Moving to a full deployment of this would depend on having details modelled that allow an NPC to act out having a life in the town in some capacity - tending crops, overseeing construction, handling cargo, a doctor, things like that.

**Comment by yaelatletl** [comment]
I'll try to keep somewhat of a log here too, today changes were made to the behavior tree and now the functions created in the Definitions file can be added to the editor

**Comment by Moonwards** [comment]
This is being done on https://github.com/RiseRobotRise/CharacterStudio , @yaelatletl?

**Comment by yaelatletl** [comment]
That's right, most progress being done on the user side, but still an important part for the backend to really work
