### ISSUE TITLE
Player collision shape size

### ISSUE THREAD

**Issue by briligg** [moonwards1/Moonwards-Virtual-Moon#27]
There are a number of places in the colony scenes where there isn't much extra space around a person-sized object. The collision shape for the player is going to need to be smaller to fit in these areas, some of which are stairs, where if it doesn't fit, it won't be able to access large areas.

For now, i've set it like this on LocalPlayer.tscn

![Screenshot from 2019-04-09 16:00:09](https://user-images.githubusercontent.com/5508441/55835919-a5a9fb00-5ae2-11e9-8d0f-9f0be24d9e12.png)

**Comment by MolbOrg** [comment]
the collision shape needs to be replaced with two small ones one for a head, another for feets, will resolve the situation

**Comment by briligg** [comment]
I tried that in order to address the problem with climbing stairs and ramps but it didn't help. That is a separate issue though.
