### ISSUE TITLE
Set up avatar customization

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#271]
The overall plan with avatars is for them to be fairly low poly,  and limited to a set of parameters that preserves a clean attractive look in-game while offering a satisfying but not distracting range of ways to customize them. Some things listed require models be built.
- [x] Picking colors of avatars - skin, hair, shirt, pants, shoes
- [x] Pick name

Related to #255

**Comment by Reousa** [comment]
Would you be able to do some research regarding scaling specific parts of the models? @Zach777

As for Image display on chests, we'll likely make that into it's own feature. It'll require some sort of persistent storage & some file management layer - likely going to wait a bit on it until we set up persistence. How does that sound? @Moonwards

**Comment by Moonwards** [comment]
@Reousa yeah, i expected that to take a while. That's fine.

**Comment by Reousa** [comment]
@KimberleyHolder can we split up the rest of the tasks in this card into their own cards?
