### ISSUE TITLE
Create a scene manager to handle loading & context management

### ISSUE THREAD

**Issue by Reousa** [moonwards1/Moonwards-Virtual-Moon#281]
Add a scene manager that provides an API to handle scene loading, switching context (between scenes etc), background loading and related matters.
- [x] Create a resource loader
- [x] Add threading

**Comment by SiudaPL** [comment]
Previous loader used both the *ResourceInteractiveLoader* and separate thread. It is available as *LevelLoader.gd* in git's history. New / refactored implementation will focus around same components, so we'll go [by the book](https://docs.godotengine.org/en/stable/tutorials/io/background_loading.html).

The *LoadingScreen.tscn* is available, contains the progress bar and probably we'll be reused.

**Comment by Reousa** [comment]
Sounds good 👌
