### ISSUE TITLE
Rewrite the logger

### ISSUE THREAD

**Issue by Reousa** [moonwards1/Moonwards-Virtual-Moon#287]
The logger should be rewritten as to use godot's stdout stream, this would allow us to use it's stack trace generation `print_debug` and friends out of the box.

Logger should have better formatting for dates & have less clutter.

The logs will have 5 levels:

`TRACE`: Informational messages that are used to depict application state status/progress & program flow.
`DEBUG`: Starting here, messages can be printed with a stack trace, using `print_debug` for example. These messages will be more granular, detailed & include useful info to debug the application.
`WARNING`: Messages to hint that an issue might be happening, but not necessarily. Issues that `WARN` do not necessarily affect the flow of the application.
`ERROR`: Messages to hint that an issue probably affects the program flow, but not necessarily.  Regardless, ERRORs are messages that require attention & need to be fixed.
`CRITICAL`: Things that definitely break the program flow, and require immediate attention. The program can not progerss past this type of error.

**Comment by SiudaPL** [comment]
Godot does have a build-in feature to write a log into a file itself. We're currently writing to file manually with File class object. I assume our logger was build upon a one that precedes this Godot feature since manual write. This will simplify the logger since code for manual write is redundant.

**Comment by SiudaPL** [comment]
- removed manual file write,
- set up Godot's automated file log,
- refactored the logger,
in [PR #320](https://github.com/moonwards1/Moonwards-Virtual-Moon/pull/320)
