### ISSUE TITLE
Chat - Create a complete chat and messaging system

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#294]
References: Second Life, Habbo. See also Group Chat, #304, Thought Bubbles #305, Messaging #306

Chat - 
- [x] Chat posts are gone after they scroll up far enough, but 50 posts  or the number of posts that fit within 5000 characters are kept at a time. They are cleared every time you log off.
- [x] The default window in the corner shows about 100 letters. If a message comes in or you start typing, it expands to say half the height of the game window, and a quarter of its width. With a hotkey, it expands to its maximum size, which is the height of the game window and a third of its width. 
- [x] Url links work. 
- [x] Pressing Shift-Lock, putting a asterisk before a post , or opening the pop-up  menu next to the chat window, will mean it is 'yelled', in which case it is visible to people up to 50 m away, takes longer to scroll off and disappear
- [ ] Chat shortcut features, also in the pop-up menu: Quiet: 3 dashes - chat available only within 3 m, Pinned: 3 asterisk: -message up to 60 char long visible as soon as someone comes in range, and disappears when they leave range Voice: 3 plus signs - voice can be used if available

**Comment by Reousa** [comment]
Can we split this into more cards? One for each feature preferably, so `Chat`, `Group Chat`, `Thought bubbles` etc.
This should allow us to review features independently & have changes in planning accordingly, also easier to follow up with
@Moonwards

**Comment by Moonwards** [comment]
I did it as one giant card because i thought it might require discussion before it was accepted as being an overall plan

**Comment by Moonwards** [comment]
@Zach777 If an asterisk is a bad choice for 'shouting', what would you suggest? Stick to Caps Lock?

Also - Tabs. How feasible are they? I think we should try to have one window only for chat, that stays in the corner, and if you have multiple conversations going on, that should be in tabs in that window.

**Comment by Zach777** [comment]
I made shouting ! . So basically an exclamation mark at the beginning shouts. We can do Caps Lock it will just not work as well as is wanted. I would like to read if a message is all caps for shouting but is not supported by Godot strings.

**Comment by Moonwards** [comment]
Ah, an ! sounds good.

**Comment by Zach777** [comment]
Tabs should be easy to do. But I will wait to implement those until after I get everything done with the public Chat.

**Comment by Reousa** [comment]
@Zach777 can we add the appropriate labels, excluding priority labels?

**Comment by Moonwards** [comment]
I don't know what criteria you used to pice the font size @Zach777, but it feels pretty large to me. It would be relaxing if it didn't take up so much of the screen.

PS i'm going to edit the comment about tabs to reflect later discussion.

**Comment by Reousa** [comment]
@Zach777 @KimberleyHolder have the features marked as finished in the task-list been finished & merged?

**Comment by Zach777** [comment]
No because this issue has not been able to be completed. I still have chat ready for when I am able to finish out the card. Alternatively we can remove the tasks that I cannot do right now.

**Comment by Reousa** [comment]
> No because this issue has not been able to be completed. I still have chat ready for when I am able to finish out the card. Alternatively we can remove the tasks that I cannot do right now.

That is the plan indeed, just need confirmation that the doable ones have been done.

**Comment by Moonwards** [comment]
At the moment no branch I have working includes chat, so I can't check on functionality.

**Comment by Reousa** [comment]
@Zach777 Could you follow up with Kim on this?

**Comment by Zach777** [comment]
Yeah of course. Would it be alright if I make a PR?

**Comment by Zach777** [comment]
@Moonwards @briligg (Sorry forgot which account I should tag) 
 I cannot complete the last task that needs listed yet. There is no way for me to know where the other players are in the game world yet. 
 I suggest leaving this PR here for now, as I have made a PR for getting an improved chat into master. The improved chat is the one that completes tasks 1-4.

**Comment by Reousa** [comment]
We'll be moving the last feature to it's own card and closing this one, then - good work! 
References: #354, #355, #357
