### ISSUE TITLE
Full scale player/avatar model.

### ISSUE THREAD

**Issue by Gyrth** [moonwards1/Moonwards-Virtual-Moon#308]
Since we're exporting all the models using .glb and at full scale the player models also need this treatment.

There is an issue though. When you apply the scale to the armature in the blend file all of the animations get messed up. Luckily the amount of animations isn't that large, so they can be remake pretty quickly.

@Reousa

**Comment by Moonwards** [comment]
I'm confused. Yes, this is the issue I had, but I thought you'd managed to export at full scale and set up the animations in Godot, @Gyrth. In which case, we had something we can use for now.

**Comment by Gyrth** [comment]
Yes, it does work. But the Armature node in Godot is at scale 10,10,10. That doesn't have any adverse effects. I just thought I'd mention it.

**Comment by Moonwards** [comment]
The scale should be fixed when we get to it, but as long as it is working I think it should be used for now. I vote to set up that player version.

**Comment by Reousa** [comment]
I'd agree with kim on that last statement, create an issue about the wrong scale, it'll be a low priority bug so long as it works, for now.

We want to get the new demo working ASAP
