### ISSUE TITLE
Errors generated on running demo with new LOD models

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#327]
This lists some of these errors together with thoughts on why they may be occurring. Because I can't clear many of them, the list is incomplete - the error list seems to cut off at 101 although there are more.

Possible reasons for different errors 
- objects that no longer contain nodes that used to exist? (HexpaneWindow_Glass, LosPortalesOUOuterWall)
--- It seemed like a good time to improve naming and refine things by combining or splitting. But often geometry and nodes that no longer exist are referenced.
- objects without an expected parent node. (Marker_MakersMonument)

**Comment by Moonwards** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5ec6b08f3c5016001672f0cf)
![image](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5ec6b0d0a24f5a001182f5f5)
This error is due to a name change in the mesh instance the collision shape is the child of. (The collision shapes are now also usually at the root level and this should be moved.)
So, either the name should be changed, or it is something in a script - I don't know why it is looking for this name.

**Comment by Reousa** [comment]
I'll take a look 👌

**Comment by Reousa** [comment]
Taking a look at this soon.

**Comment by Reousa** [comment]
Update: It appears that when a `.glb` file is re-imported into godot, it does not automatically update it's generated `.tscn` file, resulting in nodes being defined that don't exist, and vice versa.

#344 should solve this.

**Comment by Reousa** [comment]
Closing this in favor of #344
