### ISSUE TITLE
Make Interactor prefer selecting objects in front of you rather than behind you.

### ISSUE THREAD

**Issue by Zach777** [moonwards1/Moonwards-Virtual-Moon#331]

**Comment by Reousa** [comment]
@Zach777 I believe this one's been done already?

**Comment by Zach777** [comment]
No it is not. Right now the Interactor will select whatever is closest to you regardless of it being in front of or behind you. I think it would be better to get it to prefer to select things in front of you (where you are facing the camera) so you can make sure you select the interactable you want.

**Comment by Reousa** [comment]
Hmm, this could still be achievable using two areas, one for defining the range, and another differently shaped one to define the "preferable" one, WDYT?

**Comment by Zach777** [comment]
Would this even be useful anymore? Now that there is an InteractsMenu?
 Could just be beneficial to leave the interactor as is.

**Comment by Reousa** [comment]
Agreed, closing.
