### ISSUE TITLE
Getting the patch system to add and override assets/scenes.

### ISSUE THREAD

**Issue by Gyrth** [moonwards1/Moonwards-Virtual-Moon#34]
Godot has a patch system but it seems to have some issues. Here I will document my testing methods and results. It would be great if anyone can give some input because I don't know much about this system.

**Comment by Gyrth** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Figure a way Update system](https://trello.com/c/Vv4EVXw0/24-figure-a-way-update-system)

**Comment by Gyrth** [comment]
![image](https://user-images.githubusercontent.com/14081613/57558261-452a0a00-737d-11e9-9bad-d318e7089c84.png)
I made a new Scene with a new PNG and text. Exported it as 0001.pck.

**Comment by Gyrth** [comment]
![Peek 2019-05-11 00-13](https://user-images.githubusercontent.com/14081613/57559343-a48a1900-7381-11e9-8396-d91db1f66501.gif)

**Comment by MolbOrg** [comment]
and the problems was - for the history?

**Comment by Gyrth** [comment]
The problem was overriding existing assets. So for example the patch has a different background for the main menu. Same filename but different image.

**Comment by MolbOrg** [comment]
bad wording, as a description of the problem we know it, what did solve it

**Comment by TheDuriel** [comment]
@Gyrth Is this issue still relevant?

**Comment by Gyrth** [comment]
@TheDuriel no, the Updater script has changed a lot. This can be removed.
