### ISSUE TITLE
Make an Interactor manager for the Player scene to use.

### ISSUE THREAD

**Issue by Zach777** [moonwards1/Moonwards-Virtual-Moon#340]

**Comment by Zach777** [comment]
@Reousa By reading the docs, it appears that I should make a component for the player character to use. This component would be in charge of checking for the player's interact input (as Interactor itself does not handle that) and displaying info when need be.
  I think that all the Interactor should have knowledge of is the Interactor it contains and how to call InteractDisplay. It should not inherit any other properties as I think that it giving it too much for how simple it should be.

PS: I created this as a separate issue due to the fact that Interactor is meant to be used for more than just the Player.

**Comment by Reousa** [comment]
> PS: I created this as a separate issue due to the fact that Interactor is meant to be used for more than just the Player.
Correct, hence why it should be a `Component`. Even if the implementation is simple as it stands, not having the Interactor inherit `AComponent` means that neither it knows of the Entity, nor the entity knows of it. That kind of breaks our entire schema, even if the implementation is simple enough *right now* :p.

As it currently stands, the interactor should know of two things: 
1. The Entity that owns it - so it can read & modify state if need be (animation, for example).
2. The interactable it interacted with, when the action is received.

Number 2. serves as a way to implement implementation agnostic interactables, such as `AudioSpheres`. They could, for instance, inehrit the `AInteractable ` type & override it's `interacted_with` method, as an example.
In this manner, we have a baseline structure that we know must be true for all interactor -> interactable functionality.
This also means the `Entity` will only ever need a single `InteractorComponent`, to interact with *any* interactable

**Comment by Zach777** [comment]
@Reousa I am thinking of merging this issue with #326 after how you described what you wanted done with AComponent. I already have made PlayerInteractor inherit AComponent and pushed it to feat/interactor-update. Is it alright if I close this issue and make #326 encompass the closed issue's original purpose?

**Comment by Reousa** [comment]
@Zach777 Shouldn't be a problem. I'd prefer if we keep & merge new changes as is, and create a new issue + PR for the rework - since it technically extends feature. You could keep the other script/scene as a child of the `AComponent` inheriting script.

Your call though! :)
