### ISSUE TITLE
Add AudioSpheres back into Moon Town Main

### ISSUE THREAD

**Issue by Zach777** [moonwards1/Moonwards-Virtual-Moon#342]
- [x] Add AudioSpheres
- [x] Add Outdoor Audio Spheres
- [x] Create simple AudioSphere idle animation
- [x] Create animation for an Audio Sphere being interacted with

**Comment by Zach777** [comment]
@briligg I went ahead and added the AudioSpheres but I am not entirely sure what tracks to add to what AudioSpheres. Can you rename the AudioTourMarkers in Moon_Town_Master.tscn the same name as their files?

**Comment by Moonwards** [comment]
@Zach777 pinging @briligg doesn't notify me. Pinging @KimberleyHolder will work.

I did that when i added the new audio tracks. Let me check.

**Comment by Moonwards** [comment]
@Zach777 something that indicates that the AudioSpheres can be interacted with and an animation of them seems necessary. A simple animation of them is something i've always had in mind but never done. 

Also i see the audio hasn't been set up for the markers outdoors. Those can go ahead. We lack the stuff to make that part work, but the audio at least can be put in place.

**Comment by Zach777** [comment]
Should we include audio sphere animations in this issue or make a new issue for audio sphere animations?

**Comment by Reousa** [comment]
@Zach777 add them here, with the related task
