### ISSUE TITLE
Create labels for 3D Physics layers.

### ISSUE THREAD

**Issue by Zach777** [moonwards1/Moonwards-Virtual-Moon#352]
Right now their is no way to figure out what masks you are suppose to use when choosing what your 3D Physics objects use.
- [x] Add names to the layers
- [x] Determine all currently active layers

**Comment by Zach777** [comment]
@Reousa What all layers should I name? I currently have Layer 1 as World and Layer 16 as Interactions. Those are the only two layers I know off the top of my head.

**Comment by Reousa** [comment]
Just reserve one for LOD in it's next iteration, that's all for now.
