### ISSUE TITLE
Add area of interest & message ranges to chat

### ISSUE THREAD

**Issue by Reousa** [moonwards1/Moonwards-Virtual-Moon#357]
- [ ] Chat shortcut features, also in the pop-up menu: Quiet: 3 dashes - chat available only within 3 m, Pinned: 3 asterisk: -message up to 60 char long visible as soon as someone comes in range, and disappears when they leave range Voice: 3 plus signs - voice can be used if available

References: #354, #355, #351

**Comment by Zach777** [comment]
I can get to work on this as soon as an API is made for handling the range of a message. To make it simpler, I think we should filter out messages that are too far away to be heard. That way Chat itself can just focus on valid chat messages.
