### ISSUE TITLE
Give Player scene a working Interactor and get Interactor to work with the current state of the project.

### ISSUE THREAD

**Issue by Zach777** [moonwards1/Moonwards-Virtual-Moon#361]
- [x] Scale up Interactor collision shape to match the 1.0 scale.
- [x] Add Interactor to the player scene.

**Comment by Zach777** [comment]
Well it should be visible if you have visible collision shapes on.
 It is important for the audio tour though.
 The Player scene did not have an Interactor so it definitely needed me to give it one.

**Comment by Moonwards** [comment]
Oh, ok. Yes, I looked at that PR but didn't know how to actually see this. So the interactor makes interaction possible? Does it define interaction in any way?
