### ISSUE TITLE
Player moves without any contol active

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#363]
This only happens under certain circumstances but I haven't found the pattern yet. In the video below she slowly starts to move without any key being touched. It starts as a very subtle movement and slowly builds. It seems to only do this in a sideways direction.

 [vokoscreen-2020-06-02_11-09-28.mp4](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5ed67d1ac2baa0001110a4d4)

**Comment by Zach777** [comment]
I would also like to mention that I frequently have the player continue moving after I released a movement button. Sometimes the game will keep making the bug occur and sometimes the game runs flawlessly.
 Mentioning this because it might aid in the research of this bug.

**Comment by Moonwards** [comment]
@Zach777 are you on a Linux system? I have that problem, but we've discussed it before and it seemed to be something only happening to me, on my Ubuntu system.

**Comment by Zach777** [comment]
I have Ubuntu as well and that is a problem. I get a similar problem on other games even in Windows. Usually fps and third person shooter games do that to me.

**Comment by Reousa** [comment]
@Gyrth this has been fixed, yeah?

**Comment by Reousa** [comment]
Closing this - testing shows this has been fixed, we'll create a new issue if we spot the issue happening again elsewhere

**Comment by Moonwards** [comment]
I don't entirely agree that it's been fixed. It does still happen but on a scale so minor that it only causes a mild drift. However it doesn't really interfere so I agree with closing.
