### ISSUE TITLE
Make it possible to attach interactable 'cards' to objects - aka Tooltips

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#365]
Set it up so that an area can be placed on or near an object that can be clicked on, and then a pop-up window appear with text, images, or a small video, or a sound clip plays.

It would be created as a 2d UI piece, that can be dragged and closed by the player.

There was a version of this that @SiudaPL wrote, and I believe @yaelatletl worked on this at one point early on. Possibly adaptation of some of that work would be advantageous.

To expand on how things will look, there will be two main visual parts:

* One is a 2d circle with an i or a ? inside of it, kind of like that button you find that opens the help page
this will be slapped on things in the 3D overworld, so perhaps a quad with a texture on it will do (it still needs to be clickable though, so Area)
 * The other is the tooltip its self, a 2d UI box that will contain content (images, text, video) and should be resizable and have an "X" button to close it

- [x] Create the UI that would be shown upon request
- [x] Create the tooltip object (interactable) that would be assigned data to be shown

**Comment by Zach777** [comment]
@SiudaPL What progress have you made on this? If you plan on working on this, please move the card to Accepted

@Moonwards How exactly should this feature work? Should it work like an interactable that allows you to play with a window? I feel like it would be a good idea to take people using controllers into account. Clicking with a controller is next to impossible.

**Comment by Moonwards** [comment]
@Zach777 The last part is easiest - I'd be inclined to use the 'fire' button, usually the right trigger under the index finger, as the click function.

@SiudaPL is working on the format we have called slide shows. I figured that could be adapted and so I mentioned it.  But i thought this could be more like the pop-up text that appears when you activate a hotspot on an image on a website. It is one block of text, that might include an image or gif, that is attached to a particular point indicated by some small graphic element.

**Comment by SiudaPL** [comment]
@Zach777 I've planned to build mentioned *pop-up* on top of the slide showing components. Therefore it is depended upon task #364 which I'm currently doing.

**Comment by SiudaPL** [comment]
After some feedback:

The mentioned pop-up window is going to be a *Control* on a new *canvas layer* (like *HUD*) rather than in-game screens like Yael and me were working on previously.

It's best to show a semi transparent window and build the component functionality within such a frame. Zooming up on object that player is interacting with may be desired.

The *HUD*, *Control* objects will disappear with player interaction turning on / off. They always cover the screen in consistent manner. If showing up objects within a in-game screen is required one achieves such a thing with Godot's *Viewport*. Such a screen will change it's size and angle depending on player's camera position. if you further need such a functionality but with viewport responding to player's events (player manipulating in-game screens), please switch to branch *feat/slide-presentation* and build your screen on top of node *ViewportViewer*. A nested screen responding to player actions (events) is what I've been tweaking-up recently, based on Yael's work.

It isn't necessary to hold my lock on this issue, but I can get back to it shortly if no one grabs it. In case you need a nested screens, the one I've been working on are refactored and good to go.

@KimberleyHolder I think the card would still need a further directions, what exactly should be cards functionality.

**Comment by Moonwards** [comment]
* There is a 2d object that activates the pop-up. It may be activated by clicking on it after calling up the cursor by pressing Esc, but based on @Zach777  input, it may be better for players to be able to switch to in interface where there is a target symbot in the center of the game window, and they can activate items the target symbol is on with a click. 
* This means the player needs to be able to switch to a first person view - where the camera is attached to the player's head instead of being behind the player
*

**Comment by Moonwards** [comment]
@Zach777 can set up the crosshairs interface if you can do the rest @SiudaPL

**Comment by Reousa** [comment]
@Zach777 has the UI for this been created yet?

**Comment by Reousa** [comment]
@Zach777 updated the main post with description for what the visuals will appear like.

**Comment by Zach777** [comment]
@Moonwards How do you want the API setup for adding the data to the tooltip?
 Will the UI be a part of the Hud or grown out of the tooltip?

**Comment by Moonwards** [comment]
@Zach777 I'm guessing there is confusion here due to terminology. I didn't want the card to pop up in the world, i wanted it to be part of the viewer's view. What's the right way to say that? The thing that is part of the game environment is the marker that indicates card content exists

This is why this is different than billboards. You only see it if you trigger it, and it is visible only to you.

**Comment by Zach777** [comment]
Karim made that clear. I will be designing a UI element for that once I get the world element of Tooltip working. 
 There will be an icon to click on that will activate the UI element.

**Comment by Moonwards** [comment]
Then i don't understand what i'm looking at in the test scene

**Comment by Moonwards** [comment]
Although saying anything is possible instantly tempts me to put in one rabbit-hole easter egg tooltip with 17 nested cards inside it, these should almost always be one, or maybe two, 'pages' with an image and some text. Or just text, and really i can imagine a few with a short gif-type video of up to maybe 15 seconds.

I can imagine them also having links in them to websites. Not needed now, but that will happen eventually.

For now i think they only need items that open them, can go back or forward between possible multiple pages, and close them.

**Comment by Zach777** [comment]
Do you want me to make it look similar to InteractsMenu with it's center separator? 
 Left would be text and right would be the image or whatever.
Will all tooltips have material that accompanies text? Or just make it text mainly?

**Comment by Reousa** [comment]
I think it's better to make it formattable. I believe if we base it off bbtext already supports all of the requirements, excluding videos.

So in an ideal scenario, the editor would be able to add bbcode to format the entire thing.
We could have it display HTML, such as it can be linked with the website in the future.

For now though, I think the bbcode approach is enough for a start
