### ISSUE TITLE
Add vertical stairs back into Moonwards

### ISSUE THREAD

**Issue by Zach777** [moonwards1/Moonwards-Virtual-Moon#371]
Make Vertical Stairs consistent with the new guidelines of the project. The stairs should use Interactables.
Hopefully this can create discussion around how to best implement Interactables causing state changes to those that interact with them.
- [x] Add Veritcal Stairs to SceneComponents,
- [x] Make Stairs be an Interactable.
- [x] Make it easier to adjust the height of the stairs collision shape.
- [x] Get Stairs working with the new player scene.
- [x] Make mount and dismount points on the stairs.

**Comment by Moonwards** [comment]
Where does this stand right now, @Zach777 ? You are waiting on something else being done, I think, right?

**Comment by Zach777** [comment]
I thought another member of the team is working on it. I think Siuda? I got quite a lot done (the stairs actually work), just needs animations and a better editor visual system.

**Comment by Moonwards** [comment]
Yeah, @Gyrth is working on it. I just lost track of the situation. Thanks.

**Comment by Gyrth** [comment]
I've ported over the stairs climbing from the old character controller script in the branch ``feat/vertical-stairs``. I tried to separate the animation part from the actual movement. So it should follow the character guidelines. 

I haven't added an easy way of adjusting the stairs height yet. So suggestions welcome.

**Comment by Reousa** [comment]
Will give it a look 👌

**Comment by Reousa** [comment]
@KimberleyHolder @Gyrth can we get the stairs script/interactor setup on the stairs in the real Moon_Town_Master before I merge this?

**Comment by Moonwards** [comment]
@Gyrth @Reousa I have created a version of the stairs suitable for use in an array  - Assets / Moontown / Models / Vertical_Stairs / Vertical_Stairs. 

If for now this is going to be done by setting up the pieces manually, the origins of the pieces will need adjusting. I have to test how this works in Godot.
