### ISSUE TITLE
Create arrays for each Construct for the Dynamic Loading system

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#372]
This involves visually checking what is visible from each Construct and what LOD it needs to display well.

**Comment by Moonwards** [comment]
@Reousa It seems like there are a couple of bugs, although i'm not sure i'm using the tools as intended. Right now all children of Moon_Town_Master display at LOD0 by default, so i'm having trouble sorting things out. But a couple of things:

* Assigning the scene that is currently being configured to the LOD0 list seems a little glitchy, the path doesn't show in the field and on some tries the scene isn't visible during tests
* The aim would be to have nothing show up unless it is triggered by a DVT or RVT node, and it is easier for me to get what's happening if that's the case, so i'd like everything turned off by default for now, please.

**Comment by Reousa** [comment]
Marking the issues as solved as per our latest commits
