### ISSUE TITLE
A LOD2 version of Ground_Passenger_Pod is loading when it shouldn't

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#396]
When near the Airlock Bay, the Ground Passenger Pods have two versions loaded - both LOD0 and LOD2. 

![Screenshot from 2020-06-16 18-56-38.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5eed108942d4300011103573)

This is true of both of them, which belong to different RVT nodes responsible for loading the LOD0 version.  The trace showed in the in-game log doesn't indicate anywhere that a LOD2 version of the Pods has been loaded, only the LOD0. I can't find any indication of there being double objects there - the Passenger Pods exist in Moon_Town_Master only, they aren't in Airlock_Bay. There are markers for them in Airlock_Bay but they haven't been used. (This is because I anticipated replacing the 'prop' versions with rigged versions that would become vehicles. Once that happens this problem may become irrelevant because they will be replaced.)

**Comment by Reousa** [comment]
This has been fixed in a previous commit.
