### ISSUE TITLE
Use AtlasMaterial to optimize performance

### ISSUE THREAD

**Issue by yaelatletl** [moonwards1/Moonwards-Virtual-Moon#41]
AtlasMaterial can be used to optimize the draw calls, that way we could have varied materials

**Comment by Moonwards** [comment]
Are you going to work on this on your own repo?

I like the idea of getting this to the Godot team, it seems very useful to lots of projects.

**Comment by yaelatletl** [comment]
I'd like to approach godot's devs about this, as it is way too hacky to be something official, and there are issues that must be resolved, like the probable bloat of duplicate resources and the implementation of tiling textures
I'm working on this on my repo so it doesn't spam this place. Though I opened this issue for discussion to determinate the course of action

**Comment by Moonwards** [comment]
Yeah, i'm glad you did. We can use it, and i should bear in mind that you will use some of your time to work on it. Because it is generally useful, i count that as work time on Moonwards as well.

**Comment by briligg** [comment]
@yaelatletl  you posted on Discord that it turns out atlases are usually not valuable in Godot and don't offer much benefit when they are. I understood that you decided to abandon this project. Is that the case?

**Comment by yaelatletl** [comment]
Yes, unfortunately this proposal didn't go as well as I thought, at least the feedback from reduz was opportune so I didn't waste any more time on this

**Comment by TheDuriel** [comment]
Sounds like this can be archived then. 4.0 will overhaul much of this anyways. And 3.2 brings "true" atlas textures back.
