### ISSUE TITLE
Overhaul Interactables Menu

### ISSUE THREAD

**Issue by Reousa** [moonwards1/Moonwards-Virtual-Moon#410]
- [x] Fix the 'bring interact menu' string
- [x] Have the menu show/hide interactables in range as the player moves with it open, in realtime
- [x] Add the ability to hide the menu without interacting
- [x] Show and hide the mouse when the menu is shown or hidden
- [x] Add a way to set the interactables' name in the menu to other than the node-name.

**Comment by Zach777** [comment]
For this I want to make InputController handle input instead of InteractorComponent.
 May I add a Signals class called PlayerSignals.gd that has the signal for Interactor being pressed?

**Comment by Reousa** [comment]
I'd say that's valid yeah, the interacts menu should be treated as more of a general UI feature than it is specific to interactors - go for it 👍

**Comment by Zach777** [comment]
What would be the best way to handle criteria?
 Should we make it where there is a list that lets the Interactables check what they can be interacted with?
We could model it after how you name physics layers. Maybe we could have singleton that lists all criteria and Interactables can have a PoolIntArray that has it's available criteria?

 We could also have the Interactables use constants that are contained within themselves too.
