### ISSUE TITLE
Settings Menu: Add resolution options

### ISSUE THREAD

**Issue by TheDuriel** [moonwards1/Moonwards-Virtual-Moon#45]
Split from #42

**Comment by yaelatletl** [comment]
Lowering resolution should be a way for the user to be able to run the game smoothly at the cost of quality. Like here: 
![imagen](https://user-images.githubusercontent.com/28612272/65812506-7456e180-e18d-11e9-8a2d-ae61d347e063.png)
And I know, It's obviously not pretty, but it works very well for low-end laptops.

These can also be used for oversampling the game if you have a better pc: 
![imagen](https://user-images.githubusercontent.com/28612272/65812528-d6174b80-e18d-11e9-9288-d199808ec7ff.png)

See #88
