### ISSUE TITLE
Make a Billboard template, for areas with large permanent slideshows

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#451]
This is now being tracked in PR #451, Add billboard

In contrast to the pop-up explainer cards in issue #365, these billboards are always visible. 

One planned one will go by the Moonwards kiosk in First Atrium.

Once a player activates a billboard, they can advance through a series of slides with text and pictures. Video and other material may be added later, if that seems desirable.

**Comment by Zach777** [comment]
@Moonwards Do you want me to make the billboards networked for other players?
 How prominent will the billboards be? Normally I think of biiboards as being something that cycles through pictures on it's own. Not something interactable.
 Would it make more sense to call these projectors?

**Comment by Moonwards** [comment]
@Zach777 I hate it when i miss these comments. Pinging @Moonwards doesn't alert me. @KimHolder will do it. I should maybe fix that but there is weirdness with my GitKraken account.

The text that would go with the images is long enough that i think it would be better for people to go through them at their own speed. 

Networking so that all players see the same thing would be best.

**Comment by Zach777** [comment]
Is the billboard the same thing as the Makers Monument screen @briligg ?

**Comment by Zach777** [comment]
How are you envisioning it? If I get a good description I can make it tonight for you.

**Comment by Moonwards** [comment]
Where is the thing that had the arrows, and all that?

**Comment by Zach777** [comment]
That would be the ViewportViewer on the Makers Monument?  Is the Billboard similar to that?

**Comment by Moonwards** [comment]
I'm in an awkward position right now because i can't actually open anything. It's that git problem Karim is working on.

I've never actually seen that item in the game, but from what i remember, that's it. But it was never meant to be part of the Makers Monument. I was going to put one not far from there, but it is a separate thing.

**Comment by Zach777** [comment]
The item I am referencing is the screen that displays the contributors and allows you to listen to their audio clips.
 Do Billboards function similarly to that?

**Comment by Moonwards** [comment]
But that isn't what you put the arrows on - there was a screen that could display images, and it had an area underneath for displaying text.

**Comment by Moonwards** [comment]
I don't see it on the list of merged pull requests or in the current list of branches, but i remember it.

**Comment by Zach777** [comment]
Oh no, I am not saying that the Makers Monument is what you are wanting in this issue. I am saying that we have the setup for billboards pretty much already done.
 I just need to know what you want me to make it look like.

**Comment by Moonwards** [comment]
![thing.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f3eda6eab0eea0011ae35a9)

So it's this thing right? I don't know where it is in the project but it has the right functionality

**Comment by Reousa** [comment]
Just to clarify, this is what we previously called the Slide Presentation. I'll restore it's branch if it still isn't found on master

**Comment by Moonwards** [comment]
Ok, so we have it back. Cool.

I'd like to be able to add more text at the bottom. Moving apart the arrows gives a little more room, and i believe it will scroll, which might be enough. It might be necessary to tweak font size. It will need FPS in order to be properly assessed regarding that. 

Right now, what i could really use is an easy interface for adding more slides, and putting in their text and images.

**Comment by Moonwards** [comment]
Current state:

A fix was done on code shared between the Billboard and the Makers Monument, to remove an offset that made clicking on something on the Monument a bit confusing.

The Billboard is displaying images with lines across them, a sort of scanned look.

**Comment by Zach777** [comment]
What Kim said. Billboard Presentation now instances ViewportViewer instead of copy pasting the code.

 Not sure why the scanline effect is happening.

**Comment by Moonwards** [comment]
![image.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f4fd24924316d0011eb4dee)

This happened when i added text to a slide.

**Comment by Moonwards** [comment]
With that fixed, this is working well. Being able to scroll text with the mouse wheel while hovering is a very nice touch. Both the Monument and the Billboard work at the same time smoothly. 

I'd like to be able to see all the text i'm inputting, instead of just 30 letters or so at a time.

**Comment by Reousa** [comment]
> I'd like to be able to see all the text i'm inputting, instead of just 30 letters or so at a time.

Do you refer to the text displayed in the godot inspector?
