### ISSUE TITLE
Add player activation of un/docking the rover & dock animation

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#458]
This was set up previously at the end of the passenger pod farthest from the door. It was just  a dark rectangle with text instructions to press E. 

That works fine and may also be recoverable from the previous script.

**Comment by Reousa** [comment]
To add, this is to replace the currently (relatively) huge collision boxes for interacting with the rover & the pod, with more polished "interfaces" within the game world.

**Comment by Gyrth** [comment]
@Reousa added the assets in pull request #469
