### ISSUE TITLE
Establish Code guidelines

### ISSUE THREAD

**Issue by TheDuriel** [moonwards1/Moonwards-Virtual-Moon#47]
With the transition to statically typed GDScript, and the desire to involve more people in the future. It will be a good idea to establish how exactly the code in a file should be laid out.

Relevant resources:

http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_styleguide.html

http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/static_typing.html

https://www.gdquest.com/open-source/guidelines/godot-gdscript/

Within my studio we use something very close to:

```
tool
extends ClassName
class_name ClassName # Only if this is a Base Class and not a Scene
"""
	ClassName <Class|Scene> Script
	Deals with <thing>.
"""
# Comments to ignore all warnings of a type go here.
#ignore-warning-all:whatever 

# One line between variable categories
signal name 

const IDENTIFIER: type = value # ENUMs and CONSTs use CAPSCASE

enum IDENTIFIER {
		NAME,
		NAME,
		NAME
		} # Continuing lines are double indented.

export(type, limits) var identifier: type = default value setget set_func, get_func # Always declare type, and a default value.

onready var identifier: Node = $"path" # Path is always enclosed with "". Paths never go up the tree.

var _private_subclass: class_name # These are initalized and added to the tree in in _init or _ready. Tween and File for example. _ Inidcates privacy.

var public_var: type = value # Public vars that hold class references go first to group them with onready and private subclass variables.

var _private_var: type = value # _ Indicates privacy. Dont set these from outside.


func setter_func(new_value: type) -> void: # Two spaces between functions. Setters then getters.
	pass


func getter_func() -> type:
	return identifier


func _init() -> void: # Constructor. Note that overriding init looks like this: _init(arg1).(arg1) -> void: Requiring args to be duplicated.
	pass


# Virtual functions in this order:
# _enter_tree, _ready, _input, _unhandled_input, _process, _physics_process, <class_specific>, _exit_tree


func public_func() -> void: # Public functions
	pass


func _private_func() -> void: # _ indicates privacy. Dont call these from outside.
	pass


func _on_signal_name() -> void: # Signal callbacks are last
	pass
# ALWAYS have a new line at the end of your file.
```

Please share your thoughts. The goal is to establish how code should look going forwards and what the refactor of the project should look like.

**Comment by MolbOrg** [comment]
idk, I would probably prefer public functions as Caps, private as super_important, as essential interface functions are not that many, and overloading the stuff with underscores, idk. so public(Cap), protected(regular_name), private(_super_secret)

**Comment by Gyrth** [comment]
I can get behind this. The GDScript style guidelines has a bunch of other rules that I find make sense.
To get used to these style guidelines I will go over my existing scripts and apply it.

**Comment by TheDuriel** [comment]
[12:21 AM] Gyrth: @TheDuriel 

Is it enum UI_EVENTS{ or enum UIEVENTS{?

[12:22 AM] Gyrth: Are underscores allow in enum name and value?

[12:23 AM] TheDuriel: If the UI is neccecary I'd write it with _.

[12:23 AM] TheDuriel: enum UI_EVENTS {OK}

**Comment by briligg** [comment]
I think a lot in terms of what helps encourage other people to expand on Moonwards. In that case, sticking to what the community has decided is good practice is clearly valuable. It makes things comfortable for veterans, educational for beginners, and generally strengthens the whole community,
