### ISSUE TITLE
Create lunar terrain material

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#471]
Lalande crater is very young, as lunar craters go. It has a lot of small rocks on its surface. 

Something to note - in order to control dust, which is a major hazard on the moon, the surface where the colony is has been heated with concentrated sunlight and microwaves until it all fused together.  During that process, a sand mixture was sprinkled on top so that the final surface wasn't slippery. So, this surface is mostly going to be an artistic representation of that. 

If it is possible to add tiny craters procedurally, that would aid a lot with realism.

The references below serve well for the areas that remain in their natural state - most visible on either side of the road to the spaceport, for example.
https://www.lpi.usra.edu/resources/apollopanoramas/images/preview/original/JSC2007e045378.jpg
https://quickmap.lroc.asu.edu/layers?extent=-8.3030536,-4.5808771,-8.2280308,-4.5467412&proj=10&layers=NrBsFYBoAZIRnpEoAsjYIHYFcA2vIBvAXwF1Siyk44oNEQ4BmBBenfS8r0oA
https://www.lpi.usra.edu/resources/apollopanoramas/

The Pinterest page has resources that may be useful for both versions of the terrain - the fused version and the natural version. The images there link to the full resource, and includes a number of cc0 images and full PBR materials.
https://www.pinterest.com.mx/holder3884/lunar-terrain/

**Comment by Hevedy** [comment]
All the base done with distances ranges set and configurable parameters.
Noise based mixer and distance mixing for mega texture details.

**Comment by Moonwards** [comment]
![Screenshot from 2020-08-18 00-20-50](https://user-images.githubusercontent.com/50932660/90473513-b613b200-e0e8-11ea-8280-d45d5bfb3a6a.png)

Done
