### ISSUE TITLE
Create Road material

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#472]
This material would also be used for `Airlock_Bay > Bay_Grounds` and `Spaceport > Road` and `Spaceport > Terminal_Tarmac`

This material is sort of a concrete - it was laid down as molten rock with chunks and chips of other kinds of rocks in it.  It ends up looking a lot like very worn asphalt. Except it should be much lighter in color. (Unlike the current version.)

Pinterest page: 
https://www.pinterest.com.mx/holder3884/road-surface/

**Comment by Hevedy** [comment]
Noise improved, distance detail isn't need and variation is done on new noise texture.

**Comment by Moonwards** [comment]
![Screenshot from 2020-08-18 00-13-57](https://user-images.githubusercontent.com/50932660/90473128-c5dec680-e0e7-11ea-9927-ca44237cbe64.png)

Done
