### ISSUE TITLE
Create material for Factory Foundations and Launch Pads

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#473]
This is similar to the road, but a little darker - a medium light gray. Like all surfaces for vehicles or people, it needs to be rough so traction is as good as possible. These areas are made of cast stone. In this case, seams between large rectangular sections can be visible.

https://www.pinterest.com.mx/holder3884/factory-floors-and-launch-pads-cast-stone/

**Comment by Hevedy** [comment]
Reusable material done here for foundations, can be color changed and reusable for walls.

**Comment by Moonwards** [comment]
![Screenshot from 2020-08-18 00-17-29](https://user-images.githubusercontent.com/50932660/90473317-3ab20080-e0e8-11ea-8fd0-4e962861497a.png)

Done
