### ISSUE TITLE
Create materials for habitat walls

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#474]
Large parts of the walls are covered with plants. The rest has a surface created by spreading molten glass material over the cast stone during construction. A final coat is put on that is rough and textured so air plants and ivy can cling to it. That coat is also chemically a glass material, but semi-transparent and with particles in it so it is rough. An effort was made to create an interesting appearance, with varied colors. The tones are light, roughness is about 0.9.

The same plant material could be used for the roof, probably unchanged. The interior 'ground' is also covered with plants, but that would be better to be rather different - smoother and with a greater variety of plants. That is on another card, and would be an extra, if there is time.

Pinterest page:  https://www.pinterest.com.mx/holder3884/moonwards-habitat-walls-reference/

`First_Gallery_Upper_Walls` is where this goes right now. Walls of other habitats, like Center Atrium and the lower sections of First Gallery, First Atrium, and the Spaceport Terminal, also get this treatment.

The first seven items on the Pinterest page are cc0 licensed. One is a ful PBR material and there are a few others at that same website. Then there are several images that are suitable for creating a PBR material by hand. Because I couldn't find a full copyleft souce for moss, I've listed cc0 materials that could be adapted - a carpet material and a leather material.

The pottery images are references for the bare walls but can't be used as source imagery.

**Comment by Hevedy** [comment]
Walls done with a stone surface with reflections and deep simulation with layers of random placed vegetation over it and colored on different areas

**Comment by Moonwards** [comment]
![Screenshot from 2020-08-18 00-08-39](https://user-images.githubusercontent.com/50932660/90472836-0b4ec400-e0e7-11ea-8e7b-dcc6e59f8562.png)
Done,
