### ISSUE TITLE
Create materials for habitat ground floors

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#479]
The bottom of the galleries, starting with First Gallery Upper, are covered with low ground plants, mostly moss. Moss is preferred because it grows far more slowly than grass. On the moon resources for plant growth are precious, and grass isn't worth it. Moss can be walked on in the low gravity without heavy damage and so is used in place of grass. 

This will go on `First_Gallery_Upper_Foundation`

This isn't a lot different than the moss and ivy on the walls. It is less clumpy  and chunky as it is a surface meant to be walked on - sort of a long rolling lawn. 
Having other plants scattered around would be nice, but rather than being a texture, this would probably be better handled as  particles. Multimesh instance could be a solution.

There are a few resources for moss on the Pinterest page: https://www.pinterest.com.mx/holder3884/habitat-ground-level-material/
This is another resource  - https://gumroad.com/l/nCdJR

(Note - I make contributions to resource pages like these regularly. Download without guilt.)

**Comment by Hevedy** [comment]
Procedural slopes, auto noise variation and rim effect for moss.
Splatmap based painter for paths.
3 layers and per layer colors.

**Comment by Moonwards** [comment]
![Screenshot from 2020-08-18 00-04-56](https://user-images.githubusercontent.com/50932660/90472660-a7c49680-e0e6-11ea-8b71-9682b4c0bb39.png)

Done.
