### ISSUE TITLE
Add flying camera setup for easy viewing in-game

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#480]
this is needed to assess how things look and to film and take screenshots for promo material. Because the LOD system models are visible in Moon Town Master, it can't serve this purpose.

**Comment by Moonwards** [comment]
This is just a quickie. Can you set this up after you are done current tasks, Zach?

**Comment by Zach777** [comment]
Yep. Already in my queue list. I will probably do this next.
