### ISSUE TITLE
Make the player interactor be a cone facing in the direction the players' looking

### ISSUE THREAD

**Issue by Reousa** [moonwards1/Moonwards-Virtual-Moon#485]

**Comment by Zach777** [comment]
There was an issue covering this a while back.
 You should be able to interact with objects slightly behind you as well as sometimes you might want to turn it on from behind.

**Comment by Reousa** [comment]
It could have multiple collisions to reflect that yeah

**Comment by Reousa** [comment]
Closed in favor of #572
