### ISSUE TITLE
Establish project structure

### ISSUE THREAD

**Issue by TheDuriel** [moonwards1/Moonwards-Virtual-Moon#49]
As mentioned on Discord the file system of the repo could do with some work.

Right now it employs a generic "one folder per file type" workflow. However this is in conflict with Godots runtime structure and can make it difficult to associate two related files with one another.

A different approach would be to bundle related things in the same folder, and mirror the runtime structure of the project in its directories. Some things, like certain assets, may end up being used by multiple parts of the project. In those cases they can then be moved to a shared assets directory.

Below is an example of what my own projects typically look like:

```
.import
_EXPORT
	Linux-X11
	macOS
	Windows-Desktop
	.gdignore
addons
	# One subfolder per addon
	# Addons must be standalone, and capable to be fully disabled
interface
	# One folder per UI system. Like the HUD, and MainMenu
theme
	fonts
		# One subfolder per type set
		MyFont
			MyFontLicense.txt
			MyFont-Regular.ttf
			MyFont-Regular-16.tres # Name, Type, Size
	styles
		StyleBox.tres
	texture
		Logo.png
		Icon.png
	Theme.tres
shaders
	# One subfolder per shader
	MyShader
		shader.shader
		shader.material # Each material configuration
		shader-texture.png # Assets unique to the shader
shared-assets
	# Assets must be used by more than one thing, which are not otherwise related.
	Textures
	Sounds
	Models
		MyModel
			name.3dformat (fbx, dae, escn)
			# Materials, textures, and animation should be set to generate individual files in the import dialogue.
utility
	Global<Name>.gd # Singleton
	Helper<Name>.gd # Commonly instanced or purely static helper class

```

These are the "static" folders that exist in all my projects.

Individual systems are then located in their own subfolders underneath the root. Each folder contains a .tscn, .gd, and directly related assets. Subsystems are located in their own subfolders.

So for example you might have a structure like this:

```
player
	player.gd
	player.tscn
	model
		<name>.fbx
		<name>.tscn
		<name>.material
		<name>.anim
	weapon
		weapon.gd
		wepaon.tscn
```

Or like this:

```
mainmenu
	MainMenu.gd
	MainMenu.tscn
	Logo.png
	optionsmenu
		OptionsMenu.gd
		OptionsMenu.tscn
	newgamemenu
		NewGameMenu.gd
		NewGameMenu.tscn
```

Please share your thoughts on how you think the current directory structure can be improved.

**Comment by MolbOrg** [comment]
>Right now it employs a generic "one folder per file type" workflow.

not exactly correct, even if it is a mix atm for sure and needs some  cleanup
The current folder structure is more like that:

 ```
materials

```

idea was to  keep blender exported materials and all used materials in one place, to reuse and edit them in one place. not 100% so atm

```
addons
addons/HuePicker
addons/zylann.hterrain
addons/CeransDev

```
HuePicker is some old addon used to pick colors for player avatar, needs fixing was 3.0 version and crudely fixed, but works
CeransDev - some editor utlils which idk, were introduced in early days to ease some task, not that much used as of today


`scripts`

some scripts which are not tied to specific scenes, more like related to general management
needs some cleanup, like Performance* which is clearly UI element, or LoadingAreas which is some test leftover and is not used anywhere atm.

`world_environments`

some backgrounds, by @briligg 

```
scenes
scenes/blend
scenes/lightmaps
scenes/unused  <- clean up
scenes/BakedLight
scenes/BakedLight/BigAtrium
scenes/BakedLight/AtriumHab
scenes/BakedLight/FirstGalleryUpper
scenes/BakedLight/RecHab1
scenes/BakedLight/AirlockBay
scenes/meshes
scenes/cshapes

```
```
model_assets
model_assets/blend  <- would be nice to separate blender files from godot stuff, but @briligg 
model_assets/Avatars  <- most likely needs to move somewhere else, maybe
model_assets/Contributions <- most likely to move or redefine what it is and for what
model_assets/unused <- just clean up and remove after inspecting
model_assets/Scripts <- move where it belongs if used *not used, so remove
model_assets/meshes

```

Here the situation is a bit more interesting, it connected with blender files structure, and 3.0 godot and git handling tscn's. Blender files define some division of what can be considered scenes and some models which reused more often and used in scenes. 

meshes, cshapes, lightmaps, BakedLight - they are used to separate heavy stuff from tscn files to ease git diff stuff and make them more meaningful, so as to speed up a load and edit time in the editor. So tscn file mostly has references to resources. In general, those two are for static model stuff.

`documentation`

attempt to start documenting process, then later moved to it own place https://github.com/moonwards1/moonwards-docs , but all that needs work, maybe more in refactoring and after alpha finish. Would be nice to recreate godot like help stuff, could be very useful, and that was ide behind separating the stuff.

```
assets/Player
assets/Player/flycamera_ac
assets/Player/avatar_v2
assets/Player/avatar_v1
assets/Player/flycamera
assets/Player/avatar_v0
assets/Player/athlete_rover

```

different versions of avatars, current one avatar_v2, general idea was/is there can be multiple avatars (like rovers or else) to be used by player, needs more ordnung as to develop that player interface and use it and clean the place to have those which actually working.

```
img
fonts
fonts/dejavu

```
probably could be better placed

```
assets
assets/UI
assets/UI/control_elements
assets/UI/control_elements/LabelSliderMix
assets/UI/control_elements/LabelOptionButton
assets/UI/Menu
assets/UI/Options
assets/Terrain
assets/Stairs
assets/RocketDisplay
assets/Greenman
assets/Slides
assets/Slides/BucknellRocket
assets/Slides/Lunar Machines
assets/maujoe.camera_control

```

this stuff definitely a mix to sort out

`_exports`

just placeholder for export stuff, for current export_preset.conf. 3 typed of export "core" - is minimal export which is capable to dowload the rest from the server, "full" - full export, "update server" - more like server-side export. All that can benefit from cleaning what is exported. Linux, win, mac out of the necessity of zoo of systems we use on our home equipment.

`_tests`
Different test scenes, not part of end export and not needed to run the game, but more like testing and some recipes lib. Historically, out of necessity and maybe can be useful for some people
 
`_maintance`

not godot stuff, shell scripts for server and other stuff

```
themes <- a better home(?)
chat <- not used(?), old stuff
image_textures <- better home as well (?)
sounds <- hm(?)
ui <- merge with where it belongs

```

definitely to sort out

**Comment by briligg** [comment]
I've always created folders based on how things are done in Blender, and my assessment of how to make it easy to reuse things. I didn't think in terms of how things are grouped within the game. I thought in terms of having libraries of assets. Some things got set up that way for only that reason.

The list of folders in MolbOrg's post is a bit overwhelming. It looks to me like many of them can simply be deleted.

I would like to see a tree that lays out how we could update our project with a more sensible structure. I can see now that people who contribute content will tend to group things in the way TheDuriel is saying - a machine that comes with animations, textures, sounds, and scripts, say. I'm not the person to do that, but looking at the folders one by one is confusing.

**Comment by briligg** [comment]
A few thoughts:

- Can we start this process by deleting outdated content from the project so there are fewer folders and files to sift through? There are a bunch of things that clearly fall in this category
- Should we start using the Moonwards-Tests repo for things that are just proposals or are in an early development stage? And then remove the _test folder?
- I'll pare things down by moving out the .blend files, and most of the image_textures folder
- I am also going to remove a few things that seem clearly obsolete. There may be more as I don't know really how some things work.

**Comment by yaelatletl** [comment]
Would the git submodules be useful?

**Comment by briligg** [comment]
Hm?

**Comment by TheDuriel** [comment]
Submodules create dependencies, and can be confusing to non git veterans. Lets stay away from them for now.

@briligg If something can be clearly identified as dead we can purge it.

You can use personal repos to test features on and make a PR with it to let others pull and test it on their end.

**Comment by TheDuriel** [comment]
For example. The typical git workflow is:

Pull master. Branch. Develop your feature and commit. Make a pull request once its done.

**Comment by briligg** [comment]
We have a lot of bloat going on right now. I'd like to commit the removal of the .blend files and remove all the branches other than 3.1 (which shall become master) before everyone forks for doing PRs. Some of us have to deal with pretty slow internet connections.

**Comment by briligg** [comment]
I have tried to get a conversation going about how best to structure the directory tree for long term development by sketching out what we have, and a starting point for what we should move to, on a Miro board

https://miro.com/app/board/o9J_kxEte1g=/?moveToWidget=3074457346807722183
