### ISSUE TITLE
Some RVT boundaries cause the wrong loading / unloading behavior

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#490]
Some RVT / DVT nodes continue to not display the correct objects at the correct LOD level.
The default display level seems to be set at 255 (Hide), while the RVTs are designed for a default of LOD2

I am going to make a list here for the sake of organizing the issue. 

![image.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f2f09a5cbb2fc001121d203)
- This is inside RVT_First_Factory. Nothing on the lists for this RVT are showing up. 

- Use of the flying camera shows that `First Gallery Upper ` and `Overlay 1st Gal Top` are both displaying at LOD0 everywhere

**Comment by Reousa** [comment]
I see you've already fixed it in `review-dvts`, do you still need any help?

To explain the error, it means that the node with the relative path `..` to the DVT is not a LodModel, this usually means you selected the wrong node to add to the list.

**Comment by Moonwards** [comment]
@Reousa I rebased this on to master today. I fixed that one today. IIRC `..` was what was indicating 'self', but it didn't seem that way when i checked. 

But now that i'm checking the exterior RVTs, of which there are a lot, problems are showing up and so far i have not been nearly clear headed enough to have any idea what is going on. I will probably need help. But tomorrow or Thursday.

**Comment by Moonwards** [comment]
@Reousa I'll ping you in these comments to keep you updated with what i find

* A bad setting of `Hide` on the orphan node setting of the Airlock Bay  DVT was the reason for the missing items after exiting an airlock. Now fixed, my bad.

* The Rigid Body `PassengerPod` is in the list for Airlock Bay, but isn't visible. The player collides with it, so it's there. The game freezes at that point.

**Comment by Moonwards** [comment]
There are a few places that cause a lower LOD to load than it should, or that load the correct LOD, but with parts missing. 

![Screenshot from 2020-08-27 16-10-46.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f4822af3d9b050011b84f75)

Once again, the perplexing part of this is that this only happens if you exit through the airlock to the outdoors, instead of spawning outside. And this time that can't be due to the orphan node setting.

And the really weird thing is that the image above shows the correct LOD model loaded - but it is missing a few of its pieces.

At least some of those pieces were worked on in the process of improving materials. If all of them were, perhaps that is the clue that uncover the cause.

**Comment by Moonwards** [comment]
In this case, this shot was taken while the player was inside the bounds of `RVT_Rim_RadioDishEarth`. There is only one item on the lists for that RVT - the dish in the image, Radio_Dish_Earth. 

![Screenshot from 2020-08-27 17-26-30.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f4837d63d9b050011b8567b)
