### ISSUE TITLE
Rotate airlock door so they open upwards

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#495]
The rotation can be done in Godot, and i'll change the blender model so the window in the door remains in the right place.

**Comment by Moonwards** [comment]
@Reousa I have revised the airlock doors (and the airlock bay) so that the doors can swing upwards instead of sideways. And i've tried to look after setting that up in Godot. However, you have adapted that scene for the LOD system and I can't sort out how to work with it, I'm afraid.

The animations for the airlock doors just need to be rotated so they swing upwards, not sideways. I've placed the origin of the doors in the correct spot so they will move around their hinges.

**Comment by Reousa** [comment]
You can edit the animations (from within godot) through this scene: `res://SceneComponent/Object/Airlock/Airlock.tscn`

You'll find the animation player inside
