### ISSUE TITLE
Refactor GDScript code to use new Code guidelines

### ISSUE THREAD

**Issue by TheDuriel** [moonwards1/Moonwards-Virtual-Moon#50]
Locked by #47

Once the above is established. Actually do the refactor.

**Comment by Moonwards** [comment]
Remember to tick the boxes and leave any relevant comments here when this has been done for any of the script files: 
https://docs.google.com/spreadsheets/d/1fXZGY3Qw0ZNM1fZUSa3BI6S2c8Ot8dfkJpjrNNetUY4/edit#gid=0
