### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by TheDuriel** [moonwards1/Moonwards-Virtual-Moon#51]
We should establish which branches are current, and which can be retired. It might also be a good idea to revive Master as the defacto base branch.

**Comment by MolbOrg** [comment]
3.1 is current, the rest can be removed

**Comment by Moonwards** [comment]
I was working on a comment that boils down to the same thing. Let us not dwell on all the half-baked reasons and backlogged maintenance. :P

**Comment by briligg** [comment]
All branches other than 3.1 have now been deleted, and 3.1 has been renamed to 'master'.
