### ISSUE TITLE
Overhal & fix makers monument screen text being shifted upwards

### ISSUE THREAD

**Issue by Reousa** [moonwards1/Moonwards-Virtual-Moon#515]
Names in the monument are not clickable on unless you aim slightly above them. As demonstrated in this picture:
![image.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f4818db24316d0011e95b50)

The opposite applies to the "Show all" button.

Change the "Show all" name to:
"Static view"
"Interactive view", respectively, for both views.

**Comment by Zach777** [comment]
What do you mean by shifted upwards?
 I thought the buttons were what were off when clicking?

**Comment by Reousa** [comment]
@Zach777 updated the description, you can test this by trying to click on the bottom half of a name on the monument.
