### ISSUE TITLE
Viewports are occluded by shaders and post-processing

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#520]
This shows up especially on the player nametag

![Screenshot_from_2020-08-27_16-35-41.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f492d863d9b050011b89c2c)

It's also visible on the nametag when the player is looking at the sky, especially if the game window is large

![Screenshot from 2020-08-28 11-17-59.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f492e6424316d0011e9ab2d)

**Comment by Zach777** [comment]
This could possibly be caused by the Viewport not being it's own world.
 Probably just need to tinker with settings.
