### ISSUE TITLE
Fix characters not moving along with the passenger pod, when inside it

### ISSUE THREAD

**Issue by Reousa** [moonwards1/Moonwards-Virtual-Moon#527]

**Comment by Reousa** [comment]
This is now directly related to #510, due to engine limitations.

**Comment by Zach777** [comment]
Would it be possible to make the player be inside a separate "level" that just shows the windows like a camera?
 That way you do not have to deal with world movement.
Alternatively, I have worked on 2D physics systems that had to inherit another physics objects movements before. I might be able to take a crack at it without setting up a separate "level"

**Comment by Reousa** [comment]
Sure give it a shot, the next best thing I was able to come up with was to change the player to a rigidbody, which is also planned for the movement rewrite - just so it's taken into account
