### ISSUE TITLE
[TRACKER] User Interface Development

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#544]
This work is based on the design outline in the GDD, here: https://github.com/moonwards1/Moonwards-Virtual-Moon/wiki/User-Interface

The user interface in Moonwards is meant to grow into something very complex. The code for it will come in stages. Right now, the goal is to create the inteface itself so that users get an accurate, intuitive feel for how the final game will be.  Preferably, we shall add an example, a mock-up, for each function in the interface. But first we just need the complete design, then we can work on that, as we are able.

Below is an initial list of tasks that will need doing. THIS LIST IS ONLY MEANT TO HELP US REMEMBER THINGS WHILE THE DESIGN DOC IS COMPLETED.

Please add such tasks as they occur to you. We shall discuss them and come up with a road map as soon as we are able.
- [x] It will be awkward having the mouse affect the camera while you are trying to use it to select UI elements. Disable camera control with the mouse while mouse is in active mode.
- [x] We could potentially make a button you hold to control the camera with the mouse while in mouse active mode to make it easier for people to use the UI and work the camera at the same time.

**Comment by Zach777** [comment]
It will be awkward having the mouse affect the camera while you are trying to use it to select UI elements. Disable camera control with the mouse while mouse is in active mode.
 We could potentially make a button you hold to control the camera with the mouse while in mouse active mode to make it easier for people to use the UI and work the camera at the same time.

**Comment by Moonwards** [comment]
Are you able to put that in the Task list Zach? Do you have access to that?

**Comment by Zach777** [comment]
Thank you. I do have the ability to add tasks both through Github and Globoards. Did not think of doing that though.

**Comment by Zach777** [comment]
@Moonwards Do we still want to implement the button for mouse camera control?

**Comment by Zach777** [comment]
@Moonwards Is there any reason to have the button for controlling the camera? Seems pointless now with how easy it is to set the mouse activity.

**Comment by Moonwards** [comment]
Yeah, you're right.

Sorry for having missed this before.
