### ISSUE TITLE
Make Hud Crosshair Ray Cast emit mouse entered and mouse exited signals in Clickables

### ISSUE THREAD

**Issue by Zach777** [moonwards1/Moonwards-Virtual-Moon#546]
Areas in Godot have mouse_entered and mouse_exited signals. We should make first person mode emit that when they are being aimed at since we are simulating mouse functionality.

**Comment by Reousa** [comment]
Can we get a description on this? Im assuming it's to do with the Hover functionality in #516

**Comment by Zach777** [comment]
Yes. So  areas have signals provided by Godot that let them know when the mouse enters or leave them.
 Basically first person mode just needs to emit those as well to simulate the mouse (since it is acting like the same thing)
