### ISSUE TITLE
Player Interactor can interact with Interactables through walls.

### ISSUE THREAD

**Issue by Zach777** [moonwards1/Moonwards-Virtual-Moon#557]
This issue is resolved by fixing #572 

Basically the issue is that Interactor could interact through walls  because of how big the collision shape was. Now that we are switching to a RayCast we don't have to worry about implementing this functionality as much. Since the RayCast itself makes sure that it is not hitting a wall before an Interactable.

- [x] Discuss the best solution

**Comment by Zach777** [comment]
In the office space underneath town, you can start climbing the stairs from the opposite side through the walls. 
 I was thinking that the best solution to the problem would be to make a RayCast that checks to see if you have a clear view of the Interactable.

**Comment by Reousa** [comment]
Go for it 👍 
Let's make sure it only happens once the interaction is requested, though.

**Comment by Zach777** [comment]
@Reousa I thought this issue was supposed to be closed?

**Comment by Reousa** [comment]
No I was closing #485, this remains open until it's solved.
On that note, it will be solved by the PR that solves #572, they're directly related at this point.
