### ISSUE TITLE
PassengerPod2 shows as LOD2

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#558]
It's listed correctly in the corresponding RVT:
RVT_Rim_Northwest, as item 17 in the LOD0 list

The collision shapes for the RVT seem to be correct

The path to PassengerPod2 seems correct, pointing to GroundPassengerPod in the PassengerPod scene

But it shows as LOD2 when a player exits an airlock.
I can't think of anything else to check on this.

**Comment by Reousa** [comment]
It should point to `Model` as opposed to `GroundPassengerPod` 

![image](https://user-images.githubusercontent.com/18017673/93143928-311cb800-f6e9-11ea-9a73-1fb474a47edd.png)
