### ISSUE TITLE
Rework main HUD design

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#569]
An image of the current state of the draft will be updated here. This is further to #544. The section of the GDD is https://github.com/moonwards1/Moonwards-Virtual-Moon/wiki/User-Interface

![UI-v1.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f6273cf3d9b050011bf01ba)

Top left objects are finalized but may be tweaked visually  - in-game time, in-game location, friends online, and inbox.
Also bottom left - chat interface.

1 Map 
2  Building app
3. Library app
4. Events app
5 NPC app
6 Graphic novel app
7 Filming app
8 Collaborative building app

That was the intended list of apps, all of them need extensive development of their own. The Map is the easiest and clearest one, and the only one that isn't an app of its own that needs its own HUD and amounts to an entire gameplay mode.

**Comment by Moonwards** [comment]
Is the dialog box in the center going to stay? And should it be like that?

![image.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f6280293d9b050011bf0537)

It should pop up only when something activates it, right? 
Any input, @Zach777?

**Comment by Moonwards** [comment]
In looking at these, most of them refer to apps that would only be used occasionally, and if they were, they would open an entire new HUD in which parts of the normal HUD wouldn't be available.

![image.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f6280cc3d9b050011bf0563)

The things #2 through #8 were *meant* to indicate don't need to be on the screen all the time. They should be hidden in a slide-out panel unless the player wants to switch modes.

**Comment by Moonwards** [comment]
But on the other hand - the map function, and an ordinary screenshot function, and an ordinary screen recording function, would be good to have available there in the bottom right corner.

**Comment by Moonwards** [comment]
![image.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f6281e23d9b050011bf059b)

As an icon that says 'setting up for events', i don't think this really works.

**Comment by Zach777** [comment]
@Moonwards If we are going to make Interactor work the way we talked about, then we can probably remove the InteractDisplay popup there.

**Comment by Moonwards** [comment]
You don't think we might need it for something else? I can't think of anything, but i'm not sure. 

Probably better to not have it unless we need it, right? We could put it back in that case.

**Comment by Moonwards** [comment]
![image.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f6283aa3d9b050011bf0615)

After thinking about it, i think i favor a hammer here instead.

**Comment by Zach777** [comment]
For the flashlight icon, try having a stadium type looking thing.
 Since events usually mean more than average amount of people.

**Comment by Moonwards** [comment]
A stadium, huh? Maybe.
A lot of these events would be small, just for a few dozen people.

**Comment by Moonwards** [comment]
Would a balloon work?

**Comment by Hevedy** [comment]
Replaced that with a construction icon
