### ISSUE TITLE
Expression and gesture part of main HUD

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#570]
This is documented in the GDD here - https://github.com/moonwards1/Moonwards-Virtual-Moon/wiki/Player-Controls
The principle here is that by setting eyebrows, eyes, and mouth expression separately, the combination of the three give players access to hundreds of expressions, all in easy reach and intuitive. 

It was initially mocked up this way

![image.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f62870024316d0011f015a2)

Currently this menu pops up in the middle of the screen when activated

![image.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f62875e3d9b050011bf06eb)

And the initial set of mouth icons has been drafted this way

![image.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f6288da24316d0011f015fa)

**Comment by Moonwards** [comment]
The names of the radial menu items that give access to these option i think should either not be written out, or should be briefer.

Faces might replace expressions, and is a common way to say the same thing in English.
Gestures is a more precise term than actions.

**Comment by Moonwards** [comment]
The actions part of this will be worked on later, for now we'll just mock up expressions

**Comment by Moonwards** [comment]
![Screenshot from 2020-09-17 09-56-18.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f637c143d9b050011bf44cc)

This is a pretty good set but i'm going to add and change a few things.

**Comment by Hevedy** [comment]
Well the grid is complete today

**Comment by Moonwards** [comment]
Yep, the set of expressions we have now is fine for getting across the concept

**Comment by Moonwards** [comment]
We have time to do something rough for gestures, and have worked out an approach, so I'm going to list the gestures that will go in each section

#### Head (and in some cases, shoulders)

Nod
Shake head no
Tilt head to side
Tilt head back
Look away
Shrug
Hang head
Crane head forward

**Comment by Zach777** [comment]
What keyboard shortcut will be used for this? Middle mouse wheel click?
Tbh that is how I prefer to bring up quick access menus in other first person games.

**Comment by Moonwards** [comment]
That sounds good to me.
