### ISSUE TITLE
Building App HUD

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#571]
This is in the GDD here:  https://github.com/moonwards1/Moonwards-Virtual-Moon/wiki/In-game-Building-App

The current draft is as follows:

![UI-BuildingApp-Draft.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f628e2b3d9b050011bf085b)

And the initual mock up was like this - it included an object that depicted that stage of the process being done

![Screenshot from 2020-09-16 17-15-09.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f62921b3d9b050011bf093e)

**Comment by Moonwards** [comment]
![image.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f6292e83d9b050011bf0969)

Indication of which stage the process is at will be needed here, and the logic to advance through them and optionally return to previous stages.

**Comment by Moonwards** [comment]
![image.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f62936e24316d0011f01838)

This gets across the concept but the numbers should really be different, even though this is just a sketch. 

I think it can be refined so that there are only one or two such stats for each stage. 

1 - An indicator that is red if the marker reserving the lot is too close to something else or not within a permitted building area, otherwise it's green.

2 - x / 25 - indicates how close to the maximum permitted area the foundation area is. Measured in square meters. Changes to red if the maximum is exceeded.

3 - x / 32 - indicates the maximum number of vertices that can be used to create the overall shape of the structure

**Comment by Moonwards** [comment]
![BuildingApp-Controls-3.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f637b973d9b050011bf449a)

@Hevedy I'd like to add those three controls

**Comment by Hevedy** [comment]
Added, uploading
