### ISSUE TITLE
player isn't properly aligned with the vertical stairs

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#575]
The player's hand should be positioned to be on the pole, and their back is close to the bars on the outer faces of the stairs

![Screenshot from 2020-09-17 16-55-37.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f63dbcb3d9b050011bf6437)

No impaling, please.

**Comment by Reousa** [comment]
This has been fixed
