### ISSUE TITLE
Have a set of images display in the background of the start screen - part of #566

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#583]
The images would change every few seconds - something like every 6 or 8 seconds.

A set of perhaps 12 images must be created, of locations all over Moon Town, indoors and outdoors

Related - #584

**Comment by Zach777** [comment]
@Moonwards Have the images for the main menu been made yet?

**Comment by Zach777** [comment]
Is this feature still wanted? I was told that the start menu in exp/start-menu is at it's finals layout. On my screen you can no longer see the background. If the panel stays like it is, then I don't see why we should go to the effort of making alternating background images.

**Comment by Moonwards** [comment]
Heck, I didn't see the previous comment. There is something wrong with notifications i can't work out. The ping was pretty much useless. Anyhow...

Yes, this feature is still wanted. What there is in the branch must be temporary. 
The images are to come from the folder on the Google Drive. Choose any or add more, edit if you wish.

**Comment by Zach777** [comment]
Alright then. Can I add the functionality to exp/main-menu or wait?
 I assume Karim would say wait but it also kind of fits in with what Hevedy is doing now.

**Comment by Moonwards** [comment]
The intention was to have the two of you work together. So, go ahead. In fact, if you are able to work with Hevedy tomorrow, that would be useful, i think. He ended up spending most of the week on the mirror reflection and now doesn't have the time he wanted to spend on this.

**Comment by Moonwards** [comment]
Completed
