### ISSUE TITLE
Create a list of spawn points in the Start Screen Destinations - part of #566

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#585]
This could be a list that appears after a selection is made from the initial list of options in the Destination section, or it could be displayed to the right of that section.

It would be appropriate to have a few places on that list, in addition to the primary spawn point near or in the Airlock Bay

Long Dome
Spaceport
Teacup Crater

Note that except for Teacup Crater, there is no connection at the moment between those points and the main habs. While such connections are created, I'd favor putting in a button in the HUD allowing the player to return to the start menu, where they can pick another spawn point.

The issue for that is #586

**Comment by Zach777** [comment]
Should I wait for the new main menu to be developed before making this feature?

**Comment by Zach777** [comment]
Should I wait for the new main menu to be developed before making this feature?
