### ISSUE TITLE
Create a Controls settings menu in start screen - part of #566

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#589]
The list of Hotkeys will be here.

The ability to change these keys will be included here.

**Comment by Moonwards** [comment]
@Zach777 The list of controls looks complete now. The white on light gray seems a bit hard to read. Let's use the dark gray of the tabs for all gray buttons and fields. 

After that I think it's ready to PR and merge.

**Comment by Zach777** [comment]
@Moonwards @Reousa Why is this issue still open? We have a working control settings menu in the main menu now.

**Comment by Reousa** [comment]
Was probably not mentioned in PR, closing.
