### ISSUE TITLE
Refactor UpdateUI and Update_UI into a single system

### ISSUE THREAD

**Issue by TheDuriel** [moonwards1/Moonwards-Virtual-Moon#59]
core/update/Scenes/UpdateUI.tscn
core/update/Scripts/UpdateUI.gd

and

UI/Update/Updating_UI.gd
UI/Update/Updating_UI.tscn

fulfill identical purposes.

The former provides addition debug readouts, and seems overall more robust.

We should investigate merging them into a single system, and clean up the file structure while we're at it. Verbosity of debug readouts should be managed in the logger, or via build flags.

**Comment by TheDuriel** [comment]
See https://github.com/moonwards1/Moonwards-Virtual-Moon/pull/60 for initial code improvements following #47

**Comment by MolbOrg** [comment]
those are not representing implementations of the same stuff, but are frontends of underlying res://core/update/scripts/Updater.gd

core/update/Scenes/UpdateUI.tscn
core/update/Scripts/UpdateUI.gd

were made more in debug purposes and to enable testing while developing, but considering usefulness of feedback from user side trought debug messaging I think it should be used as user side of UI for the update

verbosity level is regulated in res://core/autoload/log.gd by dd_verbosity, so as what kind of messages are filtered out at specific levels of verbosity

**Comment by TheDuriel** [comment]
Sounds good. I think it would be helpful if there was a docstring at the beginning of the file explaining this.

If there is nothing relevant left in Updating_UI i suppose we could cull it? Move the stuff thats still useful to UpdateUI, and add a means of hiding debug readouts for future release builds that might not need it.

**Comment by MolbOrg** [comment]
it is not that there is nothing relevant in Updating_UI, it is that those are used in 2 different places to display and trigger an update in 2 different ways (as UI elements)

Updating_UI is @yaelatletl attempt to make what was considered user-friendly part of it

As for the amount of information printed in UpdateUI, I consider it to be a right amount atm, as it  is not for the user, but for us, if something goes wrong and in a way user can supply us a screenshot so we see where exactly it gone wrong

**Comment by Moonwards** [comment]
Am i correct that the new Launcher scripts make this obsolete?

**Comment by TheDuriel** [comment]
Yes. I'll make a new issue.
