### ISSUE TITLE
Create a Graphics settings menu in start screen - part of #566

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#590]
A specific screen size can be selected here. with further controls regarding FX, brightness and contrast, and audio.

These can all just be mocked up for now.

**Comment by Zach777** [comment]
I just realized that the issue states audio in it. Should this menu just be a graphics+audio menu?

**Comment by Moonwards** [comment]
Well, this has now been moved into a sub-menu under settings, so maybe there a separate audio menu could be created.

Honestly, i was just trying to think of good things to mock up.

**Comment by Zach777** [comment]
This has been completed correct? Why is the issue still open?

**Comment by Moonwards** [comment]
You're right. Closing.
