### ISSUE TITLE
Billboard array items load in reverse order, and arrow animations are reversed

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#609]
The arrow on the right is causing the previous slide to load, and vice versa. The animations are also flipped.

**Comment by Zach777** [comment]
What is the status on this issue @Reousa ?

**Comment by Reousa** [comment]
Resolved in #607

**Comment by Zach777** [comment]
So is this issue still relevant?

**Comment by Reousa** [comment]
No, it has been fixed, just not merged yet

**Comment by Zach777** [comment]
Okay I will move this issue to awaiting merge then in GloBoards
