### ISSUE TITLE
Player can't climb slopes and gets stuck in a few places - seems related to collision shapes

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#618]
The behavior is replicable in at least 3 places, while the player climbs in other places that seem very similar with no problem.  So I'm going to check those collision shapes in blender.

It happens when you try to climb one of the Scooter Ramps - near x: -86.85, y: 75.69, z: -188.65

![Screenshot from 2020-10-01 12-42-58.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f7617030d832b0011180a92)

The player won't climb that slope

Also near x: 12.56   y: 112.36  z: -153.02

![Screenshot from 2020-10-01 13-00-10.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f76198b0d832b0011180bb1)

The player can't climb those stairs unless she jumps onto them, after which she has to do that again  at the first landing. Also, if she jumps onto the grass area, she gets stuck in the middle. With care, she can jump off, but it isn't easy.

**Comment by Reousa** [comment]
This has been solved, yes? @Moonwards

**Comment by Reousa** [comment]
Solved
