### ISSUE TITLE
Fix what controls are editable from the Controls Settings menu

### ISSUE THREAD

**Issue by Zach777** [moonwards1/Moonwards-Virtual-Moon#673]
- [ ] Add toggle_first_person, fly up, and fly down
- [ ] Hide unstick player
- [ ] Make sure that the save file works even if the Control Settings edited buttons are changed later

**Comment by Moonwards** [comment]
There's no line for Esc, or for Shift F

**Comment by Zach777** [comment]
Shift + F is going to create more work for me. 
I can get mouse capture though.
 I will look into Shift + F.

**Comment by Moonwards** [comment]
I thought this was just about being able to change the key for activating that control. 

Instead of Shift + F to fly, maybe R, for instance.

**Comment by Zach777** [comment]
That would make it easier yeah. I would have to make new code for handling modifier keys.

 Although, if I did add modifier keys I could include Chat actions in Custom Controls. (Probably best for a later date when we add Joypad support)

**Comment by Moonwards** [comment]
I really don't want us to get into anything extra unless the payoff is big. We need to close this out as soon as we can.

The way the mouse is called up and how it works is awkward, but that's a task for another day. But someone might at least want to change the default for that to Tab from Esc, or something.

**Comment by Zach777** [comment]
Switching mouse capture button is easy. Just adding modifiers is hard lol

**Comment by Moonwards** [comment]
Yeah, so just make it another hotkey that can be changed, that's all.

**Comment by Zach777** [comment]
Done. Let me know if I need to add more keys.
