### ISSUE TITLE
Assess Lalande-baked-surface_OLD resource file

### ISSUE THREAD

**Issue by TheDuriel** [moonwards1/Moonwards-Virtual-Moon#68]
`res://materials/Lalande-baked-surface_OLD.tres` is missing a dependency

`res://materials/Normal-Lalande50.jpg`

**Comment by briligg** [comment]
I handled materials for the first while, but i think i should step back from all of this and let someone else take it over. I really don't have the knowledge or the mind set to do this well. 

So, i believe both of those are old, but i'm not really sure.
