### ISSUE TITLE
Main menu - change Apps tab menu layout

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#684]
Instead of having nested tabs, the Apps tab would look better with the layout of the Destinations tab. 

The four Apps i'd list would be Building, NPC, Events, and... maybe Library.

The icons already available for them can go in the center of each box.

Related to this, the NPC editor should open in its own window if selected in the App tab. That's Issue #685

**Comment by Zach777** [comment]
@Moonwards I was thinking about this. How will the menu account for extra apps being added in the future?
 Would a list of apps be more appropriate?

 Or just tile the apps based on how many apps are active in the project?

**Comment by Moonwards** [comment]
I was thinking of making the list scrollable. I think we'll want the space to put in icons for each. 

And several of the ones planned don't come with the game automatically, they are add ons. Like the filming app, which would extend the capabilities of the plain screengrab tool.

**Comment by Zach777** [comment]
By tileable, do you mean that there will be four apps in a grid layout?

 Or just make a list and add scrollability down the line? Either one is fine to implement.

 Grid layout could be scrollable too.

**Comment by Moonwards** [comment]
Yeah, I was thinking of a grid layout that is scrollable, two columns of tiles.

**Comment by Zach777** [comment]
@Moonwards Why is the building app a part of Main Menu? I thought building was only for constructing structures in game.

**Comment by Moonwards** [comment]
It is. The idea is people might want to work on their in game stuff without actually being in the game in any way except that.

So, if you access the app through the main menu, then it's only that, and nothing else. Nobody sees you in the game, and you only see the thing you are working on. It's like a Do Not Disturb state.
