### ISSUE TITLE
Assess HuePicker addon

### ISSUE THREAD

**Issue by TheDuriel** [moonwards1/Moonwards-Virtual-Moon#69]
`res://addons/HuePicker/clip.gd` for example is broken right now. Is this addon relevant. Is it used, if so where?

**Comment by TheDuriel** [comment]
Same with `res://addons/HuePicker/HSVPickerButton.gd`

**Comment by TheDuriel** [comment]
res://addons/HuePicker/plugin.gd is broken as well, and needs a rename

**Comment by MolbOrg** [comment]
it 3rd party addon, it has some little fixed made it work from 3.0 to 3.1 but needs more significant fixes or updating, generally, it was working in 3.1

**Comment by Gyrth** [comment]
It is used in the avatar settings. To assign different colors to each part of the avatar. Pants, hair, etc.
