### ISSUE TITLE
Chat input overlaps with other input components

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#697]
Typing things in chat will trigger the relevant input of any other active components.

**Comment by Zach777** [comment]
This is probably a @Reousa thing. Chat still lets everything know when it is typing.

**Comment by Zach777** [comment]
Why did I get assigned this issue @Reousa ? Is it not a player controls issue?

**Comment by Moonwards** [comment]
I assigned you. I'll take that off.
