### ISSUE TITLE
Driving the rover towards the crater produces a crash

### ISSUE THREAD

**Issue by yaelatletl** [moonwards1/Moonwards-Virtual-Moon#699]
Traced to this function
![imagen](https://user-images.githubusercontent.com/28612272/97246664-7c83b500-17c3-11eb-8d01-b3f4d9cd64c8.png)
![imagen](https://user-images.githubusercontent.com/28612272/97246680-83aac300-17c3-11eb-9a9a-ace6ee9f385e.png)

To reproduce: 
Enter the pod, grab a pole, drive the rover and head towards the crater's center

Edit - actually this can happen just about anywhere after you've driven for a minute or so. I'd say it happens around 10% to 15% of the time.

**Comment by Moonwards** [comment]
It turns out this sometimes happens pretty close to the airlock bay. It has happened to me twice today, the second time close to the airlocks. Same error message, with a different spatial ID.

**Comment by Moonwards** [comment]
After some testing, I believe this has now been resolved. I am unsure by what PR, maybe #762.
