### ISSUE TITLE
Interacting with a rover using a rover and later not using a rover breaks character/camera controls

### ISSUE THREAD

**Issue by yaelatletl** [moonwards1/Moonwards-Virtual-Moon#719]
As it seems, it unlinked the camera from the player, perhaps the controls too. 

Steps to reproduce: Drive a rover, go towards another, when close enough, interact with the other rover and drive it. Stop driving the rover, as a person, go to that rover and try to drive it. Your camera now looks at the first rover and you can not change it back when you stop driving it. 

![imagen](https://user-images.githubusercontent.com/28612272/97740307-b34d1a00-1aa6-11eb-8918-c05f6e36718e.png)

**Comment by yaelatletl** [comment]
Tested with master at 466692212efa7f5b97a25f64faa75a97b812851a repeating the steps now avoid the rover to be interacted, but you can later take the second rover, interact with the first rover and take over it. You can go back to the human avatar if you press the athlete rover button to dismount twice, but one of the rovers will have remanant input, moving randomly across the map

**Comment by Zach777** [comment]
@yaelatletl Was this using the relay (the sign inside the passenger pod) or interacting directly with the Rover?

 I will fix this issue. I think I should disable the ability to control a Rover from another Rover.

**Comment by yaelatletl** [comment]
Direct interaction with the rover, I didn't step in a pod in any case
