### ISSUE TITLE
There are two options.gd files

### ISSUE THREAD

**Issue by TheDuriel** [moonwards1/Moonwards-Virtual-Moon#72]
res://assets/UI/Options/Options.gd

and

res://core/autoload/options.gd

these should be renamed to avoid confusion.

**Comment by Moonwards** [comment]
I have renamed res://core/autoload/options.gd 
to res://core/autoload/autoload-options.gd

I did so simply to clear the issue. Whether we continue to use the contents here is an open question, as we are no longer trying to make the game update even during play.  If we want to do that in future. we may well want to start fresh on the job.
