### ISSUE TITLE
Make left clicking the mouse interact with interactables.

### ISSUE THREAD

**Issue by Zach777** [moonwards1/Moonwards-Virtual-Moon#724]
It feels awkward having the Interactables being interacted with by F when clickables get pressed by the mouse.
 Keep the F key but add left mouse clicking as an action for "use". (use being the action for interacting.)

**Comment by Reousa** [comment]
Update, this will now follow the following rules:

Two modes, 1st person, 3rd person.
in 1st person: 
- Interact by pressing the interact key
- Interact by left clicking
---> In both cases, the interact goes to the object the crosshair is pointing at - at the center of the screen.
in 3rd person:
- Interact by left clicking
- Interact with interacts menu (Rover exclusive)
---> We could remove the F key in this case in favor of left clicking, and you just left click on whatever object you want to interact with

**Comment by Zach777** [comment]
I though mouse could click Interactables in first person too? Not just click center of screen.

**Comment by Reousa** [comment]
It does, but it would be *at* the center of the screen, when the mouse is captured. 
I'll edit to clarify this point

**Comment by Moonwards** [comment]
This breaks the airlock doors being linked to each other so they don't both open at once. @Zach777 I guess that one is for you.
