### ISSUE TITLE
There are three player.gd files

### ISSUE THREAD

**Issue by TheDuriel** [moonwards1/Moonwards-Virtual-Moon#73]
res://assets/Player/avatar_v2/scripts/Player.gd

res://assets/Player/flycamera_ac/player.gd

res://assets/Player/avatar_v1/Player.gd

these should be renamed to avoid confusion

**Comment by MolbOrg** [comment]
it future api stuff, so entity has uniform entry point script, thye should be one case, and maybe renamed to something if it is confusing, but thye are not the same of each other.

**Comment by Gyrth** [comment]
I've renamed some player.tscn and player.gd to something more descriptive. Also I merged the player.gd scripts that were attached to the flycamera and mediamode camera into their own script. So that there is only one script per camera type.

**Comment by Gyrth** [comment]
I can't seem to run single player mode because of blocking issues in gamestate.gd so I hope this works.

**Comment by Gyrth** [comment]
I'm able to run the project again and the player script works like it should. So I think this issue can be closed.
