### ISSUE TITLE
If a game is started, then you quit to main, join server fails

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#760]
If you join a server after quitting from a local game, the game loads, but it loads showing the origin of one of the NPC characters, and stays there.

**Comment by Zach777** [comment]
By local game, you mean create custom server, @Moonwards ?

**Comment by yaelatletl** [comment]
Happens if you try to run two servers at once too 
Also, error prompted on creating a server after joining one:
ERROR: The multiplayer instance isn't currently active.
   At: modules/enet/networked_multiplayer_enet.cpp:666
