### ISSUE TITLE
Game freeze when player lets go of pole

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#761]
If a player enters the pod, anchors, and then releases the anchor, the game freezes.

![Screenshot from 2020-11-06 13-09-20.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5fa59f7e0d832b0011259e84)

**Comment by Reousa** [comment]
Fixed
