### ISSUE TITLE
Make player not fixed to camera, only root of player

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#785]
Make the root bone of the player have a fixed relationship to the camera, so that the player bobs naturally when walking and climbs and jumps with a more natural feeling movement.

**Comment by Gyrth** [comment]
I'm not sure I understand the issue. Is this just the animation of the player character that needs adjusting to bounce more up and down?

**Comment by Moonwards** [comment]
Well, yes. The player doesn't move at all in relation to the camera right now, which makes me think it isn't set up using its root bone. 

When played in Blender, the animation has a clear bobbing motion and only the root bone stays fixed. That's gone.

**Comment by Gyrth** [comment]
It does move in relation to the camera. The character just keeps looking in the same direction as the camera. Do you want the character to face in the direction it's walking to?

**Comment by Moonwards** [comment]
No, I want it to bob as it walks the same way as it does in the animation in Blender. I put a ruler on the top of the head of the character and the head moves up and down a pixel or two as it walks. The animation for this walk isn't like that. The head moves up and down quite a bit more than that. Without that it isn't very visible that this is a walking motion adapted for the moon. 

I really would have thought this means the animation is not being moved from the root bone, but from some other point. If it was moved by the root bone that motion wouldn't be virtually absent. When I look at the relevant files in the tree I can't sort out how this is being controlled so I haven't been able to determine that.
