### ISSUE TITLE
Reordering of keyboard controls

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#788]
I'm going to propose some reassignments of keys for the default layout, as I have small hands and have never been all that good at using controls. With the suggested configuration, I never have to remove all my fingers from the keyboard or look away from my screen in order to use the controls. 

- [x] Have Q and 2 move the fly camera up and down
- [x] Move E to C
- [x] Have C do double duty - calling up the cursor when an interactable menu isn't available, and if one is, then both calling that up and the cursor at the same time.
- [x] Move 3 to R
- [x] The best way to call the cursor might be to use the right mouse button

**Comment by Zach777** [comment]
I thought flying was not meant for players but only for testing? If yes then we should make flying stay as is and set custom controls for it if need be.
 Most games have E be interact, unless we change it so that left clicking interacts I suggest we do the following for defaults.

E = Interact through Ray Cast
2 or F = Interacts Menu
Right mouse button = Call cursor.
Esc = In Game options popup. (The popup that has Quit Game now)

Interacts Menu already calls the mouse.

**Comment by Moonwards** [comment]
I'm torn about the flying option. My concern is that the world is so big, it's the only way to make it likely that people will explore most of what's there. I don't think I'd want to keep it long term, but in order to get across the content there is, it might be a necessary cheat right now. It perhaps bears some testing with people to see if that's true. In the meantime I'm inclined to have it a part of normal controls.

**Comment by Moonwards** [comment]
The rest sounds fine - especially if both 2 and F stay as options

**Comment by Zach777** [comment]
Player flying is not properly networked as it is now. From the last time I checked anyway. You would have to check with Karim about that.

**Comment by Moonwards** [comment]
It doesn't need to be networked. The time I see it as legit is when someone doesn't want to take the time to drive to the Spaceport, or the Long Dome, or the solar thermal thing on the hill, but they want to see it.

Or rather, _I_ want them to see it, and get them there through the cheat.

**Comment by Moonwards** [comment]
And we agree on move 3 to R?

**Comment by Zach777** [comment]
Indifferent about 3. 

E will be interact with something through Ray Cast
R will be toggle first person
C will be bring up Interact Menu
Right mouse calls the cursor.
Q fly down, 2 fly up? I really think E should be for interacting.

Should I make Esc bring up the in game menu? The one with quit. Or it and right mouse bring up the cursor?

**Comment by Moonwards** [comment]
I think that proposal is the best compromise.

**Comment by Reousa** [comment]
> Indifferent about 3.
> 
> E will be interact with something through Ray Cast
> R will be toggle first person
> C will be bring up Interact Menu
> Right mouse calls the cursor.
> Q fly down, 2 fly up? I really think E should be for interacting.
> 
> Should I make Esc bring up the in game menu? The one with quit. Or it and right mouse bring up the cursor?

Space and ctrl, or shift and ctrl for flying up/down, when in flight mode & I think we're golden.
Also alt is commonly used in games to show/hide the cursor

**Comment by Zach777** [comment]
I thought we were going for easy access on the keyboard though? Modifiers keys are not easy access imo.

**Comment by Moonwards** [comment]
Yeah, my interest is in being able to do everything with one hand in a small area so people like me don't lose track of where the keys are and have to look down, or have trouble reaching the keys with our small hands. So alt isn't worth it to me as the cursor gets pulled up a lot.
