### ISSUE TITLE
Move interactable menu to right side of game window

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#789]
similar to how the Tooltip window is, but smaller. There should never be a need to have both open at the same time. This allows the player to see animations running without having to close the menu to do so.

**Comment by Zach777** [comment]
@briligg Will you be making TooltipButtons on the outside intended for the Rover?
 Because Interacts Menu has moved to the right it now overlaps with Tooltip Display.

Not a problem at all if Rover will never be clicking on TooltipButtons.
