### ISSUE TITLE
Add shader materials to walls, ground, and roof of First Gallery Lower

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#800]
This will just be for First_Gallery_Lower_UpperPart. The rendering cost of putting it on all of the First Gallery seems likely to be too high.

**Comment by Moonwards** [comment]
@yaelatletl I have now added the UV maps to First_Gallery_Lower_UpperPart. and created a branch for this work - `feat/add-shaders-to-fgl`

**Comment by Reousa** [comment]
@Moonwards Can you create a secondary experimental branch with it added to all FG parts, to serve as a benchmark/point of comparison.

**Comment by Moonwards** [comment]
Will do.

**Comment by Moonwards** [comment]
Resolved by PR #803.
