### ISSUE TITLE
Indicate when a player is holding a pole in the passenger pod.

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#829]
Sometimes grabbing a pole fails the first time or for whatever reason you miss when trying to grab it. Create an indicator so you know if you are holding on.

**Comment by Zach777** [comment]
I was thinking of displaying multiple small exclamation marks around the player's avatar.
 That way the player would immediately see it in 3rd person but it will not hinder the view at all.

First person players will not see it right away but it would be visible should they look down.
