### ISSUE TITLE
Audio tour of major features

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#83]
As a simple and engaging activity for early visitors, I would like us to set up a few small clickable objects near major colony features, which when clicked, play an audio file in which I talk a bit about that machine, or structure. 

This can be regarded as a stretch goal, but it is easy enough to do, and would really help. During active initial promotion I'll be keeping the game open all the time so i notice any visitor, but won't be there constantly. This helps cover things when I'm not there.

**Comment by TheDuriel** [comment]
This would involve:

Creating a ClickTrigger, built upon an Area2D. Which can independently detect if it was clicked, and then call a function within another node of the same Scene.

The base structure for a clickable Sign scene would be something like:

```
StaticBody -> Script
    CollisionShape
    MeshInstance
    ClickDetector -> Named Class, Area2D
        Connected via Signal to StaticBody. Which then controls the AudioStreamPlayer
    AudioStreamplayer3D

**Comment by Moonwards** [comment]
I'll make the little 3d marker object, pick the items that will get a clip, and make the clips.

Once i'm done we'll see who is most free to do the bit of coding it needs.

**Comment by Moonwards** [comment]
The markers for this are set up on my fork (briligg), in WorldV2.tscn

From the audio-tour Discord channel:

*The player spawns, and there is a spinning icosphere floating nearby and a text box saying if they want to go on a guided tour, click on the icosphere.
* If they don't take the tour, they can still click on any icosphere nearby them in the world and hear the audio clip that goes with it.
* if they start the tour, the icosphere moves along a path to the first marker, which is a smaller, non-animated icosphere. if the icosphere gets too far away from the player, it stops and waits. Once the player is back in range, it continues.
* The route is an issue i'm trying to work out. What makes sense is to first tour outdoors in a passenger pod under a rover, like the place the player spawns. But they would go to another rover, at another airlock, to go on that part of the tour. This depends on that being doable.
In order of preference for that - a player enters the rover, it undocks from the airlock, and the player has a 3rd person view that can orbit around so they are seeing the landscape from outside the rover, for a much better view.
- if that is too hard, make the walls of the passenger pod transparent so they can still get a good view.
* outdoors, the rover goes to each icosphere on the tour, and it has to be clickable. Is that hard? If they can see it, can they click on it? or will collision shapes get in the way? If necessary, for the outdoors, an icosphere will have to appear inside the passenger pod when the rover is in the right place, be clicked, play the audio, and the rover continues to the next marker when the guide is clicked
* animations of docking and undocking would be nice. they can be fairly simple and most of it exists,\
* once they are back at the airlock bay and leave the rover, the guide takes them to the indoor icospheres and  each one plays audio if clicked, and when the guide is clicked, it continues to the next marker
*prompts to click to continue appear when audio is finished - a combination of text on screen and glowing of the guide


Some notes

- Going to the markers by the Long Dome, the ones with 'LongDome_Extra' on the end of their names, depends on the rover going up and down that slope fine, and can be worked on after the rest is done.
- The path between Marker_Inside_3_RouteNote, and Marker_Inside_4, should go down the ramp between those floors, not down the stairs.
- Gyrth asked if marked should be skippable. That's probably a good idea

![Screenshot from 2020-02-07 19-29-50](https://user-images.githubusercontent.com/50932660/74076799-4194e380-49e0-11ea-84a9-e1d7bc663e43.png)

**Comment by Moonwards** [comment]
This has developed and been refined, so I'm going to close this issue and continue this in a new one.
