### ISSUE TITLE
Optimize rendering time for the demo

### ISSUE THREAD

**Issue by Reousa** [moonwards1/Moonwards-Virtual-Moon#834]

**Comment by Zach777** [comment]
Stairs seems to give a hit on performance when looking around. I cannot notice much of a difference on fps itself though (from Godot's monitor anyway)

 It does improve looking around with the camera though.

**Comment by Zach777** [comment]
Stairs may not be as big a deal as first thought.

 Tbh most of the issue seems to be that more items should just be completely invisible when in UFG.
Most of the other Gallerys should just be invisible. Plus there is no reason for the large areas with the open roofs being visible while in UFG.

**Comment by Moonwards** [comment]
The other galleries are all invisible unless you are in specific places in First Gallery Upper where they are visible through side windows. When you enter those areas, some of these things are loaded at a low level of detail. 

But it may be that slowdowns occur when entering and leaving those areas and that's what you are picking up on.

**Comment by Moonwards** [comment]
![image](https://user-images.githubusercontent.com/50932660/99865521-f95e4080-2b6f-11eb-8f32-457cec03d6cd.png)

These are the areas that are involved in what you are talking about. They acitvate in the upper areas of First Gallery Upper

**Comment by Zach777** [comment]
No I checked. At a stand still away from windows where you cannot see the buildings you get a performance increase from hiding them.
 I consider slowdowns when walking chug. Stand still fps are a different thing.
I know that the increasing/decreasing complexity of the models make the game chug and am not testing that at the moment.

Does free camera affect model detail? I was using that to see things but did I don't know if I should take stock into what it shows.

**Comment by Moonwards** [comment]
It isn't possible to neatly show those areas only from places where these other buildings are visible. Their existence overlaps a little into areas where they aren't. 

We could certainly trim down what is shown, but it would take some thought.

**Comment by Zach777** [comment]
Free camera has about the same fps as walking around. Using it to view things outside the hab shows that a lot of things are visible in high quality when they should not be.

**Comment by Zach777** [comment]
exp/graphics-hide-alot  shows fps if a lot of things are hidden.
 Lalande does not affect performance much.

**Comment by Moonwards** [comment]
@Reousa when the game loads, it looks like all models are loading at LOD0 - including things that shouldn't load at all when the player is in FGU.

Did you know that?
