### ISSUE TITLE
Enable functionality of the Makers Monument and attach first name and audio clip

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#84]
The Makers Monument is meant to grow as people support the project.  This functionality has to be both designed and coded. 

![Screenshot from 2020-02-21 16-00-49](https://user-images.githubusercontent.com/50932660/75075510-93029f80-54c3-11ea-9409-d3fcda5334c3.png)

 The Makers Monument is the object on the left that looks like a candle. It will be here (once the Restructure PR has been merged):
Worlds / Assets / Makers_Monument / Makers_Monument.glb

And is placed in the First_Gallery Construct

In order to make this structure accommodate an arbitrary number of names and clips in the long run, it needs to be set up so that those names display in an interesting way, so that people will want to click on the monument to view them, and then click on names to hear their audio clip.

There are a number of options for this, and at first it can be a simple version that can be made fancier in later iterations. I favor a display of names that float in space before the viewer, and that is animated in some interesting way so that it is fun to play with. Later, there will hopefully be enough names that it may need to scroll somehow. For more visual interest, possibly the monument itself should also be animated when it is active.

When it is not being used, it needs a sign to appear when someone is nearby. Optionally the object could also react to the proximity of a player in some way that invites interaction but isn't so flashy as to be distracting.  The sign should say something like 'Click me to see who is making Moonwards grow'. Something a bit catchy.

All of the names need to be clickable, which triggers their audio clip to play once. 

Right now there is only one name and one clip, so, a minimal version could be created and then expanded. If it could be accompanied by a few further placeholder names (which would be obvious placeholders, like Awesome Person 1), that would demonstrate the concept much better and look better.

The one name we have to post right now is Diane Osborne. She hasn't sent in an audio clip and i'll have to nag her about it now that it can be used.

**Comment by Gyrth** [comment]
How would this be represented in Moonwards? From my understanding it's an interactive object in the  main building. Would you like something like the rocket display? Could you draw and describe how the UI would work? 

This doesn't sound too complex, I can probably make this.

**Comment by Moonwards** [comment]
![Screenshot from 2020-02-21 16-00-49](https://user-images.githubusercontent.com/50932660/75075510-93029f80-54c3-11ea-9409-d3fcda5334c3.png)

 The Makers Monument is the object on the left that looks like a candle. It will be here (once the Restructure PR has been merged:
Worlds / Assets / Makers_Monument / Makers_Monument.glb

And is placed in the First_Gallery Construct

In order to make this structure accommodate an arbitrary number of names and clips in the long run, it needs to be set up so that those names display in an interesting way, so that people will want to click on the monument to view them, and then click on names to hear their audio clip.

(Being edited, will update shortly)

**Comment by SiudaPL** [comment]
@KimberleyHolder
Couple of questions.. 
1. How big should it be? Taller then player, slight smaller?
2. How should it be interacted with?
closed-up version may look like this
![close.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5ef9f08bf951d500124db738)
the far version might look like this (here with pop-up window)
![far_window.png](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5ef9f0b542d43000111218cd)
Which version should we focus on?
3. Both pictures assume player will interact with the Monument, pressed *use* action. Should we plan for (at least) some effects when player is just passing by?

**Comment by Moonwards** [comment]
@SiudaPL This object is pretty tall, almost 3 meters. I think have the names appear at half the height, 1.5 m above the ground. 

This monument is a special case, the best thing is for it to stand out as different.  Can you put the text on a  completely transparent background so it appears to float in front of the monument?  If the camera zooms in and it is like that, I think it will look fine for now. 

Being able to scroll through names, and being able to click on each one and have an audio clip play, are the other things that are important. 

The standard message 'Press E to interact' can appear when a player is close enough. A change in the monument at the same time would be ideal. My choice there would be that the flame rotates and pulses.

**Comment by SiudaPL** [comment]
To add the entries modify the entries dictionary on *MonumentContent.gd*. Also add the name of the audio associated with the name. The audio tracks should be put on the directory Assets/Sounds/Monument/.
