### ISSUE TITLE
Set up basic NPCs walking around the habs.

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#85]
That's it, they just walk around. 

Requires setting up Paths.

**Comment by yaelatletl** [comment]
I can take on this one

**Comment by TheDuriel** [comment]
To elaborate: Basic idea would be to use godots Path and Pathfollow node with a Tween/AnimationPlayer to do the movement.

**Comment by yaelatletl** [comment]
I already have some NPC's implementation using kinematic bodies and A* navigation, those can be easily implemented

**Comment by TheDuriel** [comment]
Can they be more easily integrated than npcs stuck on rails?

Consider the fact that they must be networked correctly.

**Comment by Moonwards** [comment]
This is being worked on in yaelatletl's fork in the NPC branch: https://github.com/yaelatletl/Moonwards-Godot/tree/NPCs

**Comment by yaelatletl** [comment]
This was adressed by #172
