### ISSUE TITLE
Change wording of Main Menu App tab sections

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#862]
Someone who got the newsletter pointed out that 'NPC editor' doesn't mean anything to most people. After looking at it, it seems to me that all of those sections could be named better.

I think this set of names work

Make Character   (instead of NPC editor)
Make Building   (instead of Buildings)
Set up Event   (instead of Events)
Open Library   (instead of Library)

**Comment by Zach777** [comment]
Make character is too similar to avatar imo.
 I assume that the people who are interested in making an npc would know what npc means. So I think NPC Creator is better.

**Comment by Moonwards** [comment]
I don't know, people who aren't game devs would hopefully be interested in learning enough to be able to make a character in the game. That would be the goal, anyways.

I can't think of a better word than 'character'.

**Comment by Zach777** [comment]
non player character? I mean will the player be able to control the npcs made in the editor?
 If yes, then npc is actually a misleading term.
More like resident creator or something.

**Comment by Moonwards** [comment]
I would think most people think of 'players' and 'characters'. And that actually it's people who know some game programming who think of 'character' as a general term that includes players.

Resident creator doesn't go far enough. Much more than that could be created. Spelling out Non-player character is an option, but it's awkward.

**Comment by Zach777** [comment]
What all can you create with this? I was thinking it was only things that would automatically following their programming. 
 So basically nothing you can directly control like the Rover.

 More like people in a village in a rpg.

**Comment by Moonwards** [comment]
Well true, it's nothing you can directly control. But that could be a lot more than people. It could be animals, robots, rovers that are portraying something, machinery. It could be a plant in a garden.

So it isn't that npc isn't accurate, it's that only game developers know what that means. The goal is to make this something that other people will also use.

**Comment by Zach777** [comment]
@Moonwards Entity creator? We would have to be very clear when we are talking about the player's avatar or the characters in world.

**Comment by Moonwards** [comment]
Yeah, entity can work. But I'm inclined more towards 'Make Entity', a more action oriented wording.
