### ISSUE TITLE
Show cursor by default at start of game

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#894]
I got feedback from my first tester that his cursor disappeared when he started the game, and he struggled to get it back. I know it's listed in the instructions, but he missed that, and I suppose that's easy to do.

So, maybe the cursor should be showing at the beginning of the game. Or otherwise it needs to be much clearer how to toggle it.

**Comment by Zach777** [comment]
What do you mean by start of game? The mouse is active when you launch the game.

**Comment by Moonwards** [comment]
When you create a local game, there is no cursor when it starts.

**Comment by Zach777** [comment]
Okay so when you click create server the mouse disappears? That was intended so that people could easily look around but I can see how that will be an issue for newcomers.
