### ISSUE TITLE
Duplicate code in Settings.gd and autoload-options.gd

### ISSUE THREAD

**Issue by TheDuriel** [moonwards1/Moonwards-Virtual-Moon#90]

**Comment by Gyrth** [comment]
Is this still an issue? I can see Settings.gd (The settings UI script) talking to autoload-settings.gd (The global settings script). And I don't see any duplicated code.

**Comment by TheDuriel** [comment]
They both still deal with saving and loading screen sizes and modes.

Overall the files are quite a mess. autoload-options seems to try to be responsible for saving and loading options in general. However settings.gd does the same.

We should probably make a single persistence singleton, using config file, which can deal with user settings. And then make the UI a controller for it. (MVC model)
