### ISSUE TITLE
Change wording of 'Destination' tab

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#911]
To be clear to the average non-gamer, a beta-tester asked me to change the names to something like:

Private game - instead of Create Server
Public game - instead of Join Master
Join private game - instead of Join Server

As suggested by Zach, making Public game the one at the top left would be better, so it's the one people understand is the usual choice. How to change the layout best for that I think needs some discussion.

**Comment by Moonwards** [comment]
'Destination' also doesn't fit with what is there. Maybe 'Game'?

**Comment by yaelatletl** [comment]
![imagen](https://user-images.githubusercontent.com/28612272/102116136-22d25b00-3e02-11eb-8df5-afbcc0134578.png)
my suggestion
