### ISSUE TITLE
Refactor file structure to follow new Asset pipeline

### ISSUE THREAD

**Issue by TheDuriel** [moonwards1/Moonwards-Virtual-Moon#94]
This mostly involves moving files, but might require breaking some assets out of their current scenes and saving them individually.

Thew new asset pipeline is described within this document:

https://docs.google.com/document/d/18STyF94Mz_zfESSMmznr7pKyuhM3J1dZfiLnGGs7t3o/edit?usp=sharing

In short:

Assets are stored in their own subfolders under `res://assets/nameofasset`. Together with their Resource files. This includes the Scene file that combines all the Resources to make the assets.

Constructs are Scenes that use Multiple Assets. And are stored in `res://constructs/nameofconstruct`. They can be grouped by theme.

Shared Resources live in `res://shared-resources/typeofresource/`.

Please read the document and don't just rely on this overview.

**Comment by TheDuriel** [comment]
Moving existing Assets is a non vital task, and can be done later or if someone is particularly bored. However new Assets should implement this workflow from the start.

**Comment by Gyrth** [comment]
I think it would be nice to have this document under the ``Wiki`` tab because it doesn't require a Google account, it's right next to the repo and markdown makes it look good/readable. I would do it, but I don't have the right permissions to do so.

**Comment by Moonwards** [comment]
Yes, that seems like a good idea. There evidently is agreement that the doc outlines a good approach. I'll move it over.

**Comment by Moonwards** [comment]
Of course, that *does* mean i'll have to finally deal with the current mess the wiki is in. :P
