### ISSUE TITLE
Change menu messages for the rover menu

### ISSUE THREAD

**Issue by Moonwards** [moonwards1/Moonwards-Virtual-Moon#967]
Here's what i'd say

`Pick up Passenger Pod`
 - `Make the rover pick up the passenger vessel. If at an airlock, the rover will dock the pod to it.`

**Comment by Zach777** [comment]
I tried telling everyone that using the Display Info for the messages was a bad idea.

 We can't have it display that without making the Interactable popup use the Title instead.
